### ISSUE TITLE
the CLASS and COMMAND fields are wrong for partitions and sub-partitionning

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#101]
One more bug found related to Table Partitioning. The CLASS and COMMAND fileds are NOT correct in partitions and sub-partitionning.

#95 only fixed the OJBECT_TYPE in partitioned table (which is the parent table).

During my testing today, I changed the parameters with belowing values:
pgaudit.log = 'ALL'
pgaudit.log_catalog = on
pgaudit.log_client = off
pgaudit.log_level = notice
pgaudit.log_parameter = off
pgaudit.log_relation = on
pgaudit.log_statement_once = off
In this case, if it is a table partitioning, both the partitioned statement and partitions statement are audited.

then I saw the CLASS and COMMAND are totally wrong.
case1: the COMMAND and CLASS wrong for partitions.
create table h(x int ,y int) partition by hash(x);
create table h_0 partition of h for values with ( modulus 2, remainder 0); 
create table h_1 partition of h for values with ( modulus 2, remainder 1); 
select * from h;
LOG:  AUDIT: SESSION,6,1,READ,SELECT,PARTITIONED TABLE,public.h,select * from h;,<not logged>
LOG:  AUDIT: SESSION,6,1,MISC,UNKNOWN,TABLE,public.h_0,select * from h;,<not logged>
LOG:  AUDIT: SESSION,6,1,MISC,UNKNOWN,TABLE,public.h_1,select * from h;,<not logged>

case2: the COMMAND and CLASS wrong for both partitions and sub-partitionning.
create table hope(x int ,y int) partition by hash(x);
create table hope_0 partition of hope for values with ( modulus 2, remainder 0) partition by hash(y); 
create table hope_0_0 partition of hope_0 for values with(modulus 2, remainder 0);
create table hope_0_1 partition of hope_0 for values with(modulus 2, remainder 1);
create table hope_1 partition of hope for values with ( modulus 2, remainder 1); 
select * from hope;

LOG:  AUDIT: SESSION,2,1,READ,SELECT,PARTITIONED TABLE,public.hope,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,MISC,UNKNOWN,PARTITIONED TABLE,public.hope_0,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,MISC,UNKNOWN,TABLE,public.hope_0_0,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,MISC,UNKNOWN,TABLE,public.hope_0_1,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,MISC,UNKNOWN,TABLE,public.hope_1,select * from hope;,<not logged>

so far, I have the solution and fixed for above 2 cases locally and could get the expected result.
LOG:  AUDIT: SESSION,2,1,READ,SELECT,PARTITIONED TABLE,public.hope,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,PARTITIONED TABLE,public.hope_0,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,TABLE,public.hope_0_0,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,TABLE,public.hope_0_1,select * from hope;,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,TABLE,public.hope_1,select * from hope;,<not logged>

BTW, would you please merge the code for my PR (fix #95 ), so that I can do continues fix based on it.
Thanks very much in advance.

**Comment by gaoxueyu** [comment]
Today I did more testing about partition table.
There is another solution for auditing partioned table and partitions.


The test scenario:
step-1: create table
CREATE TABLE h(x int ,y int) PARTITION BY HASH(x);
CREATE TABLE h_0 partition OF h FOR VALUES WITH ( MODULUS 2, REMAINDER 0);
CREATE TABLE h_1 partition OF h FOR VALUES WITH ( MODULUS 2, REMAINDER 1);

step-2: select from partitioned table
select * from h;

The audit log is as below in step-2:
AUDIT: SESSION,4,1,READ,SELECT,PARTITIONED TABLE,public.h,select * from h;,<not logged>
AUDIT: SESSION,4,1,MISC,UNKNOWN,TABLE,public.h_0,<previously logged>,<previously logged>
AUDIT: SESSION,4,1,MISC,UNKNOWN,TABLE,public.h_1,<previously logged>,<previously logged>

step-3: select from partitions
select * from h_0;

The Audit log is as below in step-3:
AUDIT: SESSION,5,1,READ,SELECT,TABLE,public.h_0,select * from h_0;,<not logged>
The audit result is correct when select from specified partitions.

There is a question in step-2, do we really need to audit h_0 and h_1 in log if user select from partitioned table?
It makes sense that we only audit for what user input, right?

so for now, there are 2 solutions for this issue:
(1) correct the "CLASS" and "COMMAND" in each of SQL queries (including both partitioned table and partitions)
(2) only audit what user inputs which means only show "AUDIT: SESSION,4,1,READ,SELECT,PARTITIONED TABLE,public.h,select * from h;,<not logged>" in log for step-2.

currently I solved the issue with first way and did some regression testing on it, but not sure if it is reasonable.
Could you please share you opinions?

**Comment by dwsteele** [comment]
It sounds to me like you should included these new fixes in #95 -- otherwise it is only a partial fix.

**Comment by gaoxueyu** [comment]
@dwsteele thanks for you response. Yes, we could combine these 2 issues.

For this bug, there are 2 solutions, would please to share you opinion on it?

(1) correct the "CLASS" and "COMMAND" in each of SQL queries (including both partitioned table and partitions) which means show 
"AUDIT: SESSION,4,1,READ,SELECT,PARTITIONED TABLE,public.h,select * from h;,
AUDIT: SESSION,4,1,MISC,UNKNOWN,TABLE,public.h_0,,
AUDIT: SESSION,4,1,MISC,UNKNOWN,TABLE,public.h_1,," in audit log when execute "select * from h;"

(2) only audit what user inputs which means only show "AUDIT: SESSION,4,1,READ,SELECT,PARTITIONED TABLE,public.h,select * from h;," in log when execute "select * from h;"

**Comment by dwsteele** [comment]
Sorry, was working from the original message in my email.

I think we only need to show the table in the query (since that's where the permissions are). So, I prefer option #2. @jconway @sfrost, thoughts?

**Comment by gaoxueyu** [comment]
@dwsteele thanks very much for your suggestion.
I discussed with my team members, we also prefer the option 2.
