### ISSUE TITLE
audit log is wrong when select from view

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#102]
Today when I select from view, I found one more audit log showed.

Test scenario:
configuration in postgres.conf
pgaudit.log = 'ALL'
pgaudit.log_catalog = on
pgaudit.log_client = off
pgaudit.log_level = log
pgaudit.log_parameter = off
pgaudit.log_relation = on
pgaudit.log_statement_once = on

step-1: create table test(x int);
step-2: create view test_view as select * from test;
step-3: select * from test_view;
AUDIT: SESSION,21,1,READ,SELECT,VIEW,public.test_view,select * from test_view;,<not logged>
AUDIT: SESSION,21,1,MISC,UNKNOWN,VIEW,public.test_view,<previously logged>,<previously logged>
AUDIT: SESSION,21,1,READ,SELECT,TABLE,public.test,<previously logged>,<previously logged>

Issue:
It works well for create view, alter view, drop view.  But I found the log in step-3(select from view) is wrong.
one more log printed "AUDIT: SESSION,21,1,MISC,UNKNOWN,VIEW,public.test_view,<previously logged>,<previously logged>"

I will debug the root cause later.

**Comment by dwsteele** [comment]
Hmmm, the view is already being logged, so I the question is why it is being logged again. This may be something in the table list that needs to be excluded.

**Comment by gaoxueyu** [comment]
Hi David, thanks for your comments.
yes, shall exclude something.
I will debug it later since I am working on other feature recent days.

**Comment by dwsteele** [comment]
Any progress on determining the cause of this?

**Comment by gaoxueyu** [comment]
Hi David,

oh , I am so sorry, I haven't updated this issue for such long time. 
And there is no progress for this issue so far.
I will consult my colleagues，but can't guarantee timeliness.

Thanks,
Hope



gaoxueyu@highgo.com
 
From: David Steele
Date: 2021-01-12 01:26
To: pgaudit/pgaudit
CC: gaoxueyu; Author
Subject: Re: [pgaudit/pgaudit] audit log is wrong when select from view (#102)
Any progress on determining the cause of this?
