### ISSUE TITLE
Feature request - enable logging per role

### ISSUE THREAD

**Issue by myappci** [pgaudit/pgaudit#103]
Hello,

I have not found it into the documentation. We have a high volume system and we need to enable audit for administration roles/users, not for the role/user running the high-volume processes.

I didn't find how to enable audit logging for dedicated created roles. So guess this would be a feature request.

Best regards,
Carsten

**Comment by dwsteele** [comment]
This is already supported (https://github.com/pgaudit/pgaudit#settings):

"Settings can be specified globally (in postgresql.conf or using ALTER SYSTEM ... SET), at the database level (using ALTER DATABASE ... SET), or at the role level (using ALTER ROLE ... SET). Note that settings are not inherited through normal role inheritance and SET ROLE will not alter a user's pgAudit settings. This is a limitation of the roles system and not inherent to pgAudit."

So, pgAudit GUCs can be assigned to whatever role you like.
