### ISSUE TITLE
Please register a recent version of pgaudit on pgxn

### ISSUE THREAD

**Issue by ludovicc** [pgaudit/pgaudit#109]
https://pgxn.org is a registry of Postgres extensions. 

pgaudit is present in this registry, but only version 1.0 is present.

**Comment by dwsteele** [comment]
pgAudit was not registered on PGXN by us. You'd need to check with Ian (ian@2ndQuadrant.com) to see if he wants to update it or remove it.

pgAudit is packaged by apt/yum.postgresql.org and many vendors so that's a better source of an up-to-date package than PGXN.
