### ISSUE TITLE
Please mention that Simon Riggs of 2ndQuadrant contributed to the design of pgaudit

### ISSUE THREAD

**Issue by simonat2ndQuadrant** [pgaudit/pgaudit#11]
Please mention that Simon Riggs of 2ndQuadrant contributed to the design of pgaudit, so its clear that this is a joint effort by both 2ndQuadrant and CrunchyData, as part of a submission of pgaudit to PostgreSQL core. Thanks

**Comment by dwsteele** [comment]
Hi Simon,

Here's what we we currently have regarding 2ndQuadrant's contribution: https://github.com/pgaudit/pgaudit/blob/master/README.md#authors.  I wasn't sure if you had seen it.

Here are my proposed changes based on what I believe you are requesting: https://github.com/pgaudit/pgaudit/compare/feature-contributor?expand=1

Have a look and let me know what you think.  Revisions are welcome, of course.

Thanks,
-David

**Comment by dwsteele** [comment]
Committed in 2a989ac3732d9486c84f287a84da44d33c8a0892.
