### ISSUE TITLE
cannot specify user to logging, logging all

### ISSUE THREAD

**Issue by bagafoot** [pgaudit/pgaudit#110]
Hi everyone,
this is configuration 
![pgaudit1](https://user-images.githubusercontent.com/30403489/87129736-79a79780-c29a-11ea-8fca-38f6bbe31227.PNG)

when I run belov command with both users postgres and test_user, both statements are logged, but I want to log only test_user actions.
` select * from tbl_test;`

![pgaudit2](https://user-images.githubusercontent.com/30403489/87130689-f8510480-c29b-11ea-9917-0aeed98b972b.PNG)

I've tried  
```
alter role postgres set pgaudit.log = 'none';
alter role test_user set pgaudit.log = 'read';
alter role test_user set pgaudit.role = 'test_user';
```
but still not working desired

what am I doing wrong ?

**Comment by bagafoot** [comment]
I've read all issues relateted, but still something is wrong, not working well, maybe it is a bug or etc...

**Comment by dwsteele** [comment]
You are not using `pgaudit.role` correctly. It does not define the user that will be logged. Instead it is used to define what actions are logged for relations that the audit role has permissions for. See https://github.com/pgaudit/pgaudit#object-audit-logging for details.

**Comment by bagafoot** [comment]
I understand, thank you.
