### ISSUE TITLE
Feature request - about replace newline ( or LF ) in SQL statement with space

### ISSUE THREAD

**Issue by auxo86** [pgaudit/pgaudit#112]
pgaudit will log executed SQL string in log message, and keep the original format ( like new line or tab ).
Here is an example:

```
select
	col1, col2, col3
from
	tabA
where
	col1 = 'ABC'
order by
	col1, col2
;
```

If I want to analyze the log by other software, like pandas, the LF will cause wrong parsing result.
Is it possible to add a config option to replace LF in SQL statement with space?
After replace LF, whole SQL statement will be in one line, and we parse the big log file will be much more easier.

Many thanks.

Auxo

**Comment by auxo86** [comment]
If we ouput with csv format, pandas.read_csv() will work correctly.

**Comment by dwsteele** [comment]
Using CSV log format is the typical solution.
