### ISSUE TITLE
Cannot start EDB postgres 9.6 with PGAudit configs on Windows

### ISSUE THREAD

**Issue by wilsondiep** [pgaudit/pgaudit#113]
I wanted to re-open the issue of Enterprise DB postgres not being able to start on windows when I have PGAudit configured.  It is the same issue as https://github.com/pgaudit/pgaudit/issues/72.  But I want to re-open, because it looks like the BigSQL version of postgres is no longer available. 

If there is any workaround or any new distributions that may have resolved this issue, that would be great.

**Comment by dwsteele** [comment]
Have you tried building with the instructions here: https://github.com/njesp/build_pgaudit_on_windows?
