### ISSUE TITLE
Is it possible to log the transaction id?

### ISSUE THREAD

**Issue by leosurwiki** [pgaudit/pgaudit#114]
I'm trying to detect the transaction boundary of our legacy code, so I will appreciate if there is a transaction id in the audit log. Is the statement id actually the tx_id while the sub_statement id actually the cid?

**Comment by dwsteele** [comment]
You can get the transaction id with `log_line_prefix`, see https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHAT
