### ISSUE TITLE
wish new trimmed logging

### ISSUE THREAD

**Issue by kutuni** [pgaudit/pgaudit#115]
hi,

i'm using docker container(postgres+audit) logging via gelf to logstash,
when the queries has newline, show output seperated to new events in kibana.

may be another logging option is clear new lines character. (trimmed)

thanks

**Comment by dwsteele** [comment]
See #112. The solution is to use CSV logging: https://www.postgresql.org/docs/13/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG
