### ISSUE TITLE
fatal error: openssl/ssl.h: No such file or directory

### ISSUE THREAD

**Issue by Fentonfi** [pgaudit/pgaudit#117]
While installing using "make install USE_PGXS=1" command we see the below error.

In file included from /usr/include/postgresql/13/server/libpq/auth.h:17:0,
                 from pgaudit.c:27:
/usr/include/postgresql/13/server/libpq/libpq-be.h:23:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'pgaudit.o' failed
make: *** [pgaudit.o] Error 1

**Comment by sharmay** [comment]
You need openssl development package:
debian/ubuntu:   **libssl-dev**
CentOS/RHEL:  **openssl-devel**

**Comment by Fentonfi** [comment]
Hi Sharmay,

Thanks for the update. That did work but I see below error

In file included from /usr/include/postgresql/13/server/libpq/auth.h:17:0,
                 from pgaudit.c:27:
/usr/include/postgresql/13/server/libpq/libpq-be.h:34:10: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'pgaudit.o' failed
make: *** [pgaudit.o] Error 1

**Comment by sharmay** [comment]
You need to find what package provides `gssapi/gssapi.h` and also any new missing files which you may encounter going forward.

**Comment by Fentonfi** [comment]
Hi Sharmay,

Thanks for the hint. I followed this https://stackoverflow.com/questions/20992032/pynfs-error-gssapi-gssapi-h-no-such-file-or-directory which worked out in installing it.
I was able to install pgaudit. Thanks a ton!!
