### ISSUE TITLE
make: *** [installcheck] Error 1

### ISSUE THREAD

**Issue by ramsrivatsa** [pgaudit/pgaudit#118]
Tests fail at a single point. 

expected.out
`NOTICE:  AUDIT: SESSION,5,2,DDL,CREATE TABLE AS,TABLE,public.tmp2,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>`
results.out
`NOTICE:  AUDIT: SESSION,6,2,DDL,CREATE TABLE AS,TABLE,public.tmp2,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>`
after SESSION, the difference between the expected and actual is 5 and 6 which causes my tests to fail. Any leads as to why?

**Comment by dwsteele** [comment]
This number indicates the number of statements submitted to the backup for processing. The number can change if the tests change or perhaps if they are run in an environment with different settings. They are only intended to work in a clean environment with `make check`.
