### ISSUE TITLE
new release for PG11?

### ISSUE THREAD

**Issue by joeri242** [pgaudit/pgaudit#119]
Hi

Can you also release a new version for postgres 11?

/johan

**Comment by devrimgunduz** [comment]
@dwsteele hi! Looks like @joeri242 is looking for this bug fix:

https://github.com/pgaudit/pgaudit/issues/64

**Comment by dwsteele** [comment]
We need to write the migration scripts before tagging. This should all be done early this week.

**Comment by dwsteele** [comment]
All the back branches have now been released.

**Comment by devrimgunduz** [comment]
Thanks! Packages are in the PostgreSQL RPM repo.
