### ISSUE TITLE
What to do when PostgreSQL is updated?

### ISSUE THREAD

**Issue by mmesantana** [pgaudit/pgaudit#120]
I have an environment with PostgreSQL 9.6 with PgAudit configured in version 1.1.3. When updating the PostgreSQL version to 10, is it necessary to update PgAudit to the corresponding version (pgaudit-1.2.1) or is it still working?
If it is necessary to update the version of PgAudit, how to proceed? Would it be to run the new installation step?

Thank you and regards.

Marcelo Santana

**Comment by dwsteele** [comment]
For a major version upgrade it is best to drop the old extension and install the new one on PG10 explicitly. It may work just by installing the package, but you'll have trouble installing bug fixes later if the version in pg_extension is not correct.
