### ISSUE TITLE
ERROR:  not fired by event trigger manager

### ISSUE THREAD

**Issue by XABUNO** [pgaudit/pgaudit#121]
Hello,

I have created a short version of the test script sql/pgaudit.sql in this repo:

`
\set VERBOSITY terse

-- Create pgaudit extension
CREATE EXTENSION IF NOT EXISTS pgaudit;

CREATE TABLE tmp (id int);
CREATE TABLE tmp2 AS (SELECT * FROM tmp);

-- Make sure events don't get logged twice when session logging
SET pgaudit.log = 'all';
SET pgaudit.log_client = ON;
SET pgaudit.log_level = 'notice';

--CREATE TABLE tmp (id int);
--CREATE TABLE tmp2 AS (SELECT * FROM tmp);

-- Reset log_client first to show that audits logs are not set to client
RESET pgaudit.log_client;

--DROP TABLE tmp;
--DROP TABLE tmp2;

RESET pgaudit.log;
RESET pgaudit.log_level;
RESET pgaudit.log_directory;

DROP TABLE tmp;
DROP TABLE tmp2;

`

When I run it, I always get an error saying "ERROR:  not fired by event trigger manager" whenever a command is trying to create a table. (For example, "CREATE TABLE tmp (id int, data text);" at line 11) 

However, if I put the commands before the 3 lines of setting those parameters, the tables can be created successfully. Also, a similar issue happens when the tables are being dropped. The tables can only be successfully dropped when the dropping commands are put after the resetting commands.  Maybe this means the table creating and dropping only work with the default parameters?

 I am running psql 11 on RHEL 8. I downloaded the binary PGAudit 1.3.2 package from https://centos.pkgs.org/8/postgresql-11-x86_64/pgaudit13_11-1.3.2-1.rhel8.x86_64.rpm.html 

Update: encountered same issue on RHEL 7 running postgres 11

**Comment by dwsteele** [comment]
Is `pgaudit` listed in `shared_preload_libraries`? See: https://github.com/pgaudit/pgaudit#settings.
