### ISSUE TITLE
pgaudit.c:13:33: fatal error: access/htup_details.h: No such file or directory

### ISSUE THREAD

**Issue by vkhvorostianyi** [pgaudit/pgaudit#122]
I found the same issue earlier but it's not fixed, I did exactly all the steps in the Vagrant file and it didn't help. 
Env RHEL7, PG10

**Comment by vkhvorostianyi** [comment]
https://github.com/pgaudit/pgaudit/issues/57

**Comment by vkhvorostianyi** [comment]
Found the solution 
`sudo make USE_PGXS=1 PG_CONFIG=/usr/pgsql-11/bin/pg_config install`
https://github.com/tds-fdw/tds_fdw/blob/master/InstallCentOS.md

**Comment by dwsteele** [comment]
Added your suggestion for `PG_CONFIG` at fd4319f7c8e215a4f29.
