### ISSUE TITLE
`make check USE_PGXS=1` doesn't work in build instructions

### ISSUE THREAD

**Issue by dwsteele** [pgaudit/pgaudit#123]
`make check USE_PGXS=1` requires a PG source tree. This should be changed to either `installcheck` or removed.

**Comment by zano-aa** [comment]
HI there,
I can't installed anything because the command there are not working anymore and because of a contrib directory as well I'm a bit confused anyone got something to say ?

**Comment by motte** [comment]
For what it's worth, I played around with this to build an alpine image.  You can run `make installcheck USE_PGXS=1`, like @dwsteele suggests, after `make INSTALL USE_PGXS=1`.  However, it requires you to set root, which requires greater security considerations.  I would recommend skipping `make installcheck` and consider a functional test(s) to ensure pgaudit is properly installed.

**Comment by motte** [comment]
I'm unable to link the PR to this issue, but this should close with #124
