### ISSUE TITLE
pgaudit logs all activities regardless of the role parameter

### ISSUE THREAD

**Issue by doronyaary** [pgaudit/pgaudit#127]
Hello,

I have installed pgaudit @ postgresql 10. These are the parameters I changed in postgresql.conf:

```
pgaudit.log = 'ALL'
pgaudit.role = 'mygroup'
```

This is the `\du` output:

```
  Role name  |                         Attributes                         | Member of
-------------+------------------------------------------------------------+-----------
 magic       |                                                            | {}
 mygroup     | Cannot login                                               | {}
 postgres    | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 simon       |                                                            | {mygroup}
```

The issue is that pgaudit captures all of the DDL/DML for **all of the users** and not just for users in the "mygroup" group.
For example, this is several steps I did to simulate the issue:

```
psql -h 1.1.1.1 -U postgres
postgres=# create table test_table(id int);
CREATE TABLE
```

Then, when I investigate the logs - I see the following line:

`2020-11-25 15:34:35.485 CET [54325] postgres@postgres LOG:  AUDIT: SESSION,2,1,DDL,CREATE TABLE,TABLE,public.test_table,create table test_table(id int);,<not logged>`

My question, is why do I see the DDLs/DMLs from the user "postgres" when the role parameter actually says "mygroup" - which postgres is not a member of it? Just be clarify, when I am logging in with the user "magic" the same happens while this user is not from the "mygroup" role.

Thanks!

**Comment by dwsteele** [comment]
What is audited is the intersection of these settings. So, if you set `pgaudit.log = 'ALL'` then everything will be audited.
