### ISSUE TITLE
Dedicated SET ROLE audit CLASS

### ISSUE THREAD

**Issue by mbanck** [pgaudit/pgaudit#129]
I think `SET ROLE` commands are a prime target to be audited. They are included in `MISC` and (for pgaudit 1.4 and up, I wonder why the other branches did not receive that feature?) `MISC_SET`; however, lots of application servers issue `SET application_name` or similar things for every connection and/or transaction and those can make it prohibitive to enable `MISC(_SET)`. So (if technically even possible) having a dedicated class (like `ROLE_SET`) for `SET ROLE` (or it be also included in the `ROLE` class) would be nice.

I realize that the separate `set_user` extension exists, but this is another library to preload and might not be enabled by cloud vendors, contrary to (the now pretty popular) pgaudit.

**Comment by dwsteele** [comment]
> I wonder why the other branches did not receive that feature?

We don't back patch features to prior versions. Stability is very important for this extension.

> So (if technically even possible) having a dedicated class (like ROLE_SET) 

This is not possible (as far as I can tell) without parsing the statement. SET is the finest grain we get from PostgreSQL.

However, I could be mistaken or perhaps things have changed that would allow it. This is a feature we would be interested in so feel free to investigate.
