### ISSUE TITLE
Permission denied on Ubuntu 14.04

### ISSUE THREAD

**Issue by rdnkrkmz** [pgaudit/pgaudit#13]
I run :
**postgres@toshiba:/usr/local/pgsql/bin$** ./pgaudit_analyze --daemon /usr/local/pgsql/data/pg_log

**then get :**

Unable to open log file: Permission denied at ./pgaudit_analyze line 633.
 at ./pgaudit_analyze line 44.
    main::**ANON**('Unable to open log file: Permission denied at ./pgaudit_analy...') called at /usr/share/perl/5.18/Carp.pm line 101
    Carp::confess('Unable to open log file: Permission denied') called at ./pgaudit_analyze line 633

Am I doing something wrong?
I compiled the pgaudit with postgresql 9.5.3 source code, then I copy the pgaudit_analyze under $PGHOME/bin and, lib folder to $PGHOME/lib then run the above code.
Also I install perl dbi:pg driver.
Thanks lot.

**Comment by dwsteele** [comment]
It looks like a basic permissions error.  You are running pgaudit_analyze as `postgres` but are you sure `postgres` has permissions on the entire path `/usr/local/pgsql/data/pg_log`.  Is the cluster possibly running as another user?

**Comment by rdnkrkmz** [comment]
Thank for reply: 
Here ps putput, cluster runngin as potgres.
postgres@toshiba:/usr/local/pgsql/data/pg_log$ **ps -ef | grep postgres**

postgres  4469 16108  0 01:51 pts/5    00:00:00 ps -ef
postgres  4470 16108  0 01:51 pts/5    00:00:00 grep postgres
postgres  9571 31692  0 Haz17 ?        00:00:00 postgres: pg95: postgres postgres 127.0.0.1(36776) idle
root     16076 15919  0 01:35 pts/5    00:00:00 su postgres
postgres 16108 16076  0 01:35 pts/5    00:00:00 bash
postgres 31692     1  0 Haz17 ?        00:00:00 /usr/local/pgsql/bin/postgres
postgres 31699 31692  0 Haz17 ?        00:00:00 postgres: pg95: logger process  
postgres 31701 31692  0 Haz17 ?        00:00:00 postgres: pg95: checkpointer process  
postgres 31702 31692  0 Haz17 ?        00:00:00 postgres: pg95: writer process  
postgres 31703 31692  0 Haz17 ?        00:00:00 postgres: pg95: wal writer process  
postgres 31704 31692  0 Haz17 ?        00:00:00 postgres: pg95: autovacuum launcher process  
postgres 31705 31692  0 Haz17 ?        00:00:00 postgres: pg95: stats collector process

Then, permissions for the folder pg_log

**postgres@toshiba:/usr/local/pgsql/data/pg_log$** ll
total 32K
-rw------- 1 postgres postgres   96 Haz 17 23:07 2016-06-17_230719.log
-rw------- 1 postgres postgres 3,3K Haz 17 23:12 2016-06-17_230719.csv
-rw------- 1 postgres postgres   96 Haz 17 23:12 2016-06-17_231251.log
-rw------- 1 postgres postgres 2,2K Haz 17 23:15 2016-06-17_231251.csv
-rw------- 1 postgres postgres   96 Haz 17 23:15 2016-06-17_231549.log
-rw------- 1 postgres postgres  12K Haz 17 23:59 2016-06-17_231549.csv
-rw------- 1 postgres postgres    0 Haz 18 00:00 2016-06-18_000000.log
-rw------- 1 postgres postgres    0 Haz 18 00:00 2016-06-18_000000.csv

Is that something strange?

**Comment by dwsteele** [comment]
That all looks good to me.

I think I see the issue but I don't have the time to debug it this weekend.  I'll look at it first thing on Monday and see if I can figure what's going on.

**Comment by rdnkrkmz** [comment]
I think, I found the problem.
In short just I changed the application's logging folder from **/var/log/pgaudit_analyze.log** to **/tmp/pgaudit_analyze.log**, after many hours, worked. :-)
But Monday I will test it on RHEL6 Vmware. I will share my experience then.

Detailed explanation is below.

I followed these steps :

postgres $> **sudo apt-get install libdbd-pg-perl** # pg driver.
postgres $> **sudo cpanm Tk.pm** # debug tool dependency
postgres $> **sudo cpanm Devel::ptkdb** # debug tool
postgres $> perl -d:ptkdb pgaudit_analyze # here I set paths manually in script
(here get the same error.)

Then I checked the folder **/var/log**, I saw that, only **root** and **syslog** group can write the folder, so we, as postgres user can't write app's log.
But apllication's output is confusing because I had understood that app can not read the *.csv files. Debugging show that it is incorrect. 
Here permission for **/var/log** folder.

ridonekorkmaz@toshiba:/var$ ll
total 44K
.
.
.(escaped rows)
.
**drwxrwxr-x 17 root syslog   4,0K Haz 18 02:46 log**
drwxrwxrwt  2 root root     4,0K Haz 18 04:53 tmp

Then I tried this command;
postgres@toshiba:/usr/local/pgsql/bin$ touch /var/log/test.log
**touch: cannot touch ‘/var/log/test.log’: Permission denied**

Above result I got. **So that is proven app can't create its own log file, nothing more.** 
Then I changed the logging folder from /var/log/pgaudit_analyze.log to /tmp/pgaudit_analyze.log worked properly.

All after that, I run and it worked. Also I checked in DB that logs are coming:
**postgres $> pgaudit_analyze --daemon /usr/local/pgsql/data/pg_log**

**Comment by dwsteele** [comment]
The error message has been improved at https://github.com/pgaudit/pgaudit_analyze/commit/197cbc0bc87f22120951db2fb4b37a849b81e74e.

Note that the pgaudit_analyze project has moved to a new repo: https://github.com/pgaudit/pgaudit_analyze
