### ISSUE TITLE
Will not build on Win10

### ISSUE THREAD

**Issue by neillindberg** [pgaudit/pgaudit#134]
I'm running PG12, but the closest stable release is REL_11_STABLE.

I follow instructions, but cannot get past the first step in running `make check`.

Is this project only for Linux systems?

lindben@STLLINDBENW101 MINGW64 /c/Program Files/PostgreSQL/12/contrib/pgaudit (REL_11_STABLE)
$ make check USE_PGXS=1
process_begin: CreateProcess(NULL, pg_config --pgxs, ...) failed.
Makefile:15: pipe: No error
make: *** No rule to make target 'check'.  Stop.

**Comment by dwsteele** [comment]
You could try the instructions at: https://github.com/njesp/build_pgaudit_on_windows/blob/master/README_12.1.md
