### ISSUE TITLE
Pgaudit stack is not empty

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [pgaudit/pgaudit#136]
When running a query like this:

```sql
SELECT function('CREATE SEQUENCE a;','bigint');
```

I am getting "pgaudit stack is not empty error". It seems that this is because CREATE commands are not skipped here https://github.com/pgaudit/pgaudit/commit/671dd2a628e3ea7bc56f662c9b07d574546f5aeb#diff-732f45c2566567903ce7d398b6a6a35131e40d9eb81dfa4f37a2201c630884e2R1373.

Is this expected that I am getting this error, and what is leading to this error?

**Comment by dwsteele** [comment]
Are you sure you are running the most recent version of pgAudit? This was fixed in 1.4.1, etc: https://github.com/pgaudit/pgaudit/releases

**Comment by SaitTalhaNisanci** [comment]
I was running into this but this was because of a problem in our extension, which we fixed now. No longer running into this. Thanks
