### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jasonk876** [pgaudit/pgaudit#139]
Not sure the if this is the place I should ask this question, I am getting an error when installing pgAudit through dnf.

Does anyone know how I can fix this?

dnf  install pgaudit14_12-1.4.1-1.rhel8.x86_64.rpm
Updating Subscription Management repositories.
Last metadata expiration check: 0:13:23 ago on Mon 12 Apr 2021 03:43:53 PM CDT.
pgaudit14_12.rpm                                                                           2.5 MB/s |  52 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides postgresql12-server needed by pgaudit14_12-1.4.1-1.rhel8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by dwsteele** [comment]
Looks like you need to install all the required packages manually or install the yum repo from https://yum.postgresql.org. The latter is probably easier.

**Comment by jasonk876** [comment]
Thank you that helped! I was thinking "postgresql12-server" was referring to the postgresql database and not a different required package.

Thanks again, I greatly appreciate it.
