### ISSUE TITLE
pgaudit.role settings

### ISSUE THREAD

**Issue by rdnkrkmz** [pgaudit/pgaudit#14]
Hi,
I want to audit log user DML activities.
**My problem is:** A user who I do not want to audit log, is audited when does a DML on a table which is audited for another user over "pgaudit.role" setting.

I understood that "pgaudit.role" setting is used for a master role for auditing. 
I do such a work:
Created a "auditor" role, t1 and t2 user, and a table called "a";

```
postgres=# CREATE ROLE auditor;
postgres=# CREATE USER t1 WITH PASSWORD 'aaa';
postgres=# CREATE USER t2 WITH PASSWORD 'aaa';
postgres=# GRANT USAGE ON SCHEMA postgres TO t1;
postgres=# GRANT USAGE ON SCHEMA postgres TO t2;
postgres=# CREATE TABLE A(a numeric);  --(in postgres schema as postgres user)
postgres=# GRANT INSERT ON a to t1;
postgres=# GRANT INSERT ON a to t2;

```
Now, we are here, one role, two user and a table.

Here my pgaudit settings in postgresql.conf
```
pgaudit.log_catalog = off
pgaudit.log_parameter = on
pgaudit.role = 'auditor'
```
Then, I tried to insert something in "a" table as t1 user, nothing is audit logged (well)
After that, I grant t1 user to auditor role,

`postgres=# GRANT t1 to auditor;`

Then, I tried to insert something in "a" table as t1 user, insert is audit logged (well)

BUT, when I tried to use user t2, (without granting to auditor) t2's inserts also audited. (why)

Is it the way that extension works?
Or Am I doing something wrong?

**Update:**
When I revoke t1 from auditor, then nothing is audit logged (well).

Thanks a lot.

**Comment by dwsteele** [comment]
Auditing is based on object permissions that are assigned to the audit role, so if you want to audit inserts then:
```
grant insert on a to auditor;
```
You've done this indirectly by granting insert to t1 and then granting that role to the auditor.  Now any insert to table a will be audited.  Try granting what you want to audit directly to the auditor role.

**Comment by rdnkrkmz** [comment]
Thanks for reply:
According to your explanations; I have to use auditor, instead of user "t1".
But I want to audit t1 and t2 **user**. Not just auditor.
The point of my view is auditing user dml ops, on a user basis, not a DML ops. basis.

Is it possible?

**Comment by dwsteele** [comment]
You can do this with `alter role set pgaudit.role = ...` as specified here: https://github.com/pgaudit/pgaudit#settings.  This way you can create an audit role per user.

I don't recommend this as it is quite a bit more fragile.  Role GUCs are not inherited so it is easy to create a new role that has no auditing without you realizing it.
