### ISSUE TITLE
logs only DELETE and TRUNCATE statements

### ISSUE THREAD

**Issue by asyd** [pgaudit/pgaudit#140]
Hello folks,

I'm wondering if it possible to logs only `DELETE` and `TRUNCATE` statements?

As far as I understand the documentation, logging `DELETE` implies to log `INSERT` and `UPDATE` as well which are not possible in our workload.

Thanks you!

**Comment by dwsteele** [comment]
Logging DELETE-only is possible using object audit logging, see: https://github.com/pgaudit/pgaudit#object-audit-logging. But that won't work for TRUNCATE so I don't think it is possible to log *only* DELETE and TRUNCATE.
