### ISSUE TITLE
Would it be possible to log in a table rather than in a file

### ISSUE THREAD

**Issue by antoinerl** [pgaudit/pgaudit#143]
Hi,
Thanks for the good job!
Our main issue with that extension is that logs are logged in the standard postgres log file... and we need that logs in our database. For GDPR requirements we would like to store the access logs (READ) to sensitive data into the database itself to be able to track them easily.
Would it be possible? Difficult? 
Maybe other people might be interested in such an evolution? Or a fork?

Antoine RL

**Comment by dwsteele** [comment]
It is not possible for pgAudit to do this directly because any rollback/error would result in audit entries being lost.

See https://github.com/pgaudit/pgaudit_analyze for a way to get audit data into tables.
