### ISSUE TITLE
V 1.5 crashes Postgres 13

### ISSUE THREAD

**Issue by jswhal** [pgaudit/pgaudit#147]
I had trouble installing the extension after compiling on VS 19. Postgres said it couldn't find the pgaudit_ddl_command_end function in the dll. I created a .def file and exported it and pgaudit_sql_drop. Now, as soon as I try to add the extension, Postgres crashes:

LOG:  server process (PID 22152) was terminated by exception 0xC0000005
2021-06-20 11:37:57.823 EDT [25344] DETAIL:  Failed process was running: CREATE EXTENSION pgaudit
	    SCHEMA audit
	    VERSION "1.5";

this is my dumpbin output

C:\TAP\pgaudit-master\pgaudit\x64\Debug>dumpbin /EXPORTS pgaudit.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30038.1
Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file pgaudit.dll

File Type: DLL

  Section contains the following exports for pgaudit.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           5 number of functions
           5 number of names

    ordinal hint RVA      name

          1    0 00011244 Pg_magic_func = @ILT+575(Pg_magic_func)
          2    1 00011145 pg_finfo_pgaudit_ddl_command_end = @ILT+320(pg_finfo_pgaudit_ddl_command_end)
          3    2 00011131 pg_finfo_pgaudit_sql_drop = @ILT+300(pg_finfo_pgaudit_sql_drop)
          4    3 000113C5 pgaudit_ddl_command_end = @ILT+960(pgaudit_ddl_command_end)
          5    4 0001139D pgaudit_sql_drop = @ILT+920(pgaudit_sql_drop)

  Summary

        1000 .00cfg
        1000 .data
        2000 .idata
        1000 .msvcjmc
        3000 .pdata
        5000 .rdata
        1000 .reloc
        1000 .rsrc
       10000 .text
       10000 .textbss

**Comment by jswhal** [comment]
There is also a warning on ilist.h
Warning	C28182	Dereferencing NULL pointer. 'node->next' contains the same NULL value as 'head->head.next' did. 	pgaudit	C:\Program Files\PostgreSQL\13\include\server\lib\ilist.h	307	

dlist_push_head(dlist_head *head, dlist_node *node)
{
	if (head->head.next == NULL)	/* convert NULL header to circular */
		dlist_init(head);

	node->next = head->head.next;
	node->prev = &head->head;
	node->next->prev = node;
	head->head.next = node;

	dlist_check(head);
}

**Comment by dwsteele** [comment]
Sorry, not sure how I missed this, but I'm afraid I can't be much help since I don't work in Windows. You should probably have a look at: https://github.com/njesp/build_pgaudit_on_windows.
