### ISSUE TITLE
SELECT ... FOR UPDATE not logged

### ISSUE THREAD

**Issue by shinderuk** [pgaudit/pgaudit#149]
Tested on REL_13_STABLE.

```
postgres=# set pgaudit.log_client = on;
SET
postgres=# set pgaudit.log_level = notice;
SET
postgres=# set pgaudit.log = 'all';
NOTICE:  AUDIT: SESSION,1,1,MISC,SET,,,set pgaudit.log = 'all';,<not logged>
SET
postgres=# set pgaudit.log_relation = on;
NOTICE:  AUDIT: SESSION,2,1,MISC,SET,,,set pgaudit.log_relation = on;,<not logged>
SET
postgres=# select * from t1;
NOTICE:  AUDIT: SESSION,3,1,READ,SELECT,TABLE,public.t1,select * from t1;,<not logged>
 a 
---
 1
(1 row)

postgres=# select * from t1 for update;
 a 
---
 1
(1 row)
```

I guess this is an unintended effect of https://github.com/pgaudit/pgaudit/commit/33248d2222cbb11c45da2ab61bbb855658836d7d

**Comment by dwsteele** [comment]
Yes, this certainly looks like a regression from the prior behavior. This branch shows that reverting brings back this functionality.

Thoughts, @petere?

**Comment by shinderuk** [comment]
FWIW, reading through https://github.com/pgaudit/pgaudit/pull/88 I noticed that the original Peter's patch attempted to fix the misclassification of SELECT FOR UPDATE as UPDATE. But then the patch was reworked and the bug introduced.

**Comment by dwsteele** [comment]
Yeah, that's pretty much what happened. I was confused about what the patch was supposed to do and didn't get any feedback on my update. Of course it did not help that we had no test for this case.

PR#151 attempts to remedy this. Please have a look.
