### ISSUE TITLE
Not logging "internal" statements?

### ISSUE THREAD

**Issue by aharonrobbins** [pgaudit/pgaudit#15]
Hi.  Consider a statement like:

create temporary table t_table as select whatever from real_table;

This logs three different kinds of statements: select, insert, and "create table as".  Is there a way to avoid logging the "internal" statements (select, insert) and just get the original query?

Thanks!

**Comment by dwsteele** [comment]
You could use pgaudit.log = 'ddl' to log only the create statement, but you won't get other select/insert statements.  I see that you are saying, but in practice it would be very hard to determine which statements were important and which were not.

**Comment by aharonrobbins** [comment]
Thanks for the reply.  I had about come to the same conclusion but thought I’d double check with you.

Aharon

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]
