### ISSUE TITLE
pgAudit "No such file or directory"

### ISSUE THREAD

**Issue by jasonk876** [pgaudit/pgaudit#150]
I am getting this error 'FATAL:  58P01: could not access file "pgaudit": No such file or directory' when trying to use pgAudit with postgreSQL 12. 

I installed the pgaudit package from RedHat and pgAudit is located in /usr/pgsql-12/lib/bitcode/pgaudit. I added pgaudit to this line "shared_preload_libraries = 'pgaudit'" in postgresql.conf configuration file.

Is there a step that I am missing?

**Comment by dwsteele** [comment]
I haven't seen this before. Perhaps a path issue -- why is `bitcode` in there?

**Comment by jasonk876** [comment]
that is the path of where it installed from the RedHat RPM package I used.

**Comment by dwsteele** [comment]
We are not involved with packaging. Perhaps take this up with RedHat?

**Comment by jasonk876** [comment]
okay, thank you!
