### ISSUE TITLE
PgAudit Logging pgaudit inserts

### ISSUE THREAD

**Issue by wcardoso** [pgaudit/pgaudit#152]
Hi, i'm using PgAudit 1.4 on Postgres 12 in RHEL.

"pgaudit.log"	"write, ddl"
"pgaudit.log_catalog"	"on"
"pgaudit.log_client"	"off"
"pgaudit.log_level"	"log"
"pgaudit.log_parameter"	"off"
"pgaudit.log_relation"	"on"
"pgaudit.log_statement_once"	"off"
"pgaudit.role"	

But its logging all insert on the tables from schema pgaudit, in less of 24 hours my log increase so much that is impossible of commit all changes in the table.

E.g:

![image](https://user-images.githubusercontent.com/28545235/129212992-c2552ceb-4253-4848-9ae4-07f740e47b05.png)

The most logs where from pgaudit inserts.

**Comment by dwsteele** [comment]
You not being auditing the user that maintains the `pgaudit` schema.
