### ISSUE TITLE
could not load library pgaudit during pg_upgrade from 10 to 11

### ISSUE THREAD

**Issue by geovansb** [pgaudit/pgaudit#153]
I am upgrading my postgresql from 10.18 to 11.13. I already have installed the new version of pgaudit:

rpm -qa | grep pgaudit
pgaudit13_11-1.3.2-1.rhel7.x86_64
pgaudit12_10-1.2.2-1.rhel7.x86_64

rpm -qa | grep postgresql | grep server
postgresql10-server-10.18-1PGDG.rhel7.x86_64
postgresql11-server-11.13-1PGDG.rhel7.x86_64

But, during the check upgrade i am receiving this error:
Checking for presence of required libraries                 fatal

$ cat loadable_libraries.txt
could not load library "$libdir/pgaudit": ERROR:  pgaudit must be loaded via shared_preload_libraries

In the postgresql.log i see this messages:
 ERROR:  pgaudit must be loaded via shared_preload_libraries
 STATEMENT:  LOAD '$libdir/pgaudit'

I have other extension (pg_cron) that is OK during check upgrade.

I know that is possible to uninstall extension from previous version and, after upgrade, install on new version of postgresql. But i think this is not the best aprouch because i may loose some configuration.

Could you help me to identify whats is wrong in check upgrade for pgaudit?

**Comment by dwsteele** [comment]
Looks like you did not add pgaudit to `shared_preload_libraries`, see: https://github.com/pgaudit/pgaudit#settings

**Comment by geovansb** [comment]
Hi, you was right. I thought that pg_upgrade will copy everything (include the libraries config). But, after you told me this I had think about and does make sense that i have to configure the shared_preload_libraries in the new cluster. 
After change shared_preload_libraries in postgresql.conf, everything is OK and pg_upgrade --check looks like this:
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for presence of required libraries                 ok
Checking database user is the install user                  ok
Checking for prepared transactions                          ok
Checking for new cluster tablespace directories             ok
*Clusters are compatible*

Thank you for your support. I really was confused about this but now I understood the symptom and the root cause.
