### ISSUE TITLE
PgAudit 1.3.1 on RDS - COMMAND field now gives value as SELECT which was earlier giving BIND.

### ISSUE THREAD

**Issue by basant-gurung** [pgaudit/pgaudit#154]
Hey Guys,

Earlier the 8th field i.e COMMAND, used to give BIND as the value for auditing SELECT queries. But now it is giving SELECT as follows.

2021-09-03 07:06:25.331 UTC,"postgres","mydb",22224,"111.222.333.444:50683",6131c926.56d0,1,"SELECT",2021-09-03 07:05:10 UTC,12/42,0,LOG,00000,"AUDIT:OBJECT,1,1,READ,SELECT,TABLE,dgm_schema.dgm_table,""select * from .....

Is there something I am missing or these changes are done recently?

Please help!

**Comment by dwsteele** [comment]
1.3.1 is not the most recent release, though I don't think 1.3.2 (released October 2020) would change anything. `SELECT` is the correct command in this case so it may be something that was fixed in RDS. I suggest you take it up with Amazon if this is an issue.

**Comment by basant-gurung** [comment]
Quite possible. Because the strange thing is that 4 months ago, on the same Postgres 11.10 + pgAudit 1.3.1 it was auditing as BIND. And now it's auditing SELECT.
