### ISSUE TITLE
Upgrade path after pg upgrade

### ISSUE THREAD

**Issue by jankatins** [pgaudit/pgaudit#155]
We would like to add pgaudit to [Aiven for PostgreSQL](https://aiven.io/postgresql). One issue we ran in was that there is no automatic upgrade path when upgrading postgresql itself.

I can basically see two ways for us to get a smooth upgrade experience:

* If pgaudit is in used, DROP extension, upgrade pg, remove pgaudit.log config, CREATE extension, set pgaudit.log back to what it was before
* Add an artificial (empty, as all pg functions are the same over all versions I checked) upgrade path script for all versions earlier than what is in the branch (a bit of annoyance to maintain)

We would prefer the latter, but I'm unsure if this is omitted by design?

If not by design: would you take PRs adding it to the respective branches? Basically in 1.3 -> allow upgrades from all versions in 1.2 by adding the respective `pgaudit--1.2.{0,1}--1.3.0.sql` and similar for 1.4, 1.5, and 1.6 branches (only from all previous released versions)? I would probably follow the postgis idea of simply maintaining the list of previous releases and generating these files in the makefile.

**Comment by dwsteele** [comment]
> Add an artificial (empty, as all pg functions are the same over all versions I checked) upgrade path

This is true now but won't be soon. We need to do some security updates in this area.

It might be better to wait for those and see how that would affect this plan. They should be coming very soon.

**Comment by jankatins** [comment]
Looking forward to it... thanks for the heads up!

**Comment by dwsteele** [comment]
New releases are out.
