### ISSUE TITLE
Logging object access from security definer functions

### ISSUE THREAD

**Issue by oschwald** [pgaudit/pgaudit#157]
We are looking to log all access to several relations in our database. We were hoping to do this using the object audit logging. For the general case, this seemed to work well.

However, we have several security definer functions that query these tables. With these functions, pgAudit will only log uses of the table when the creator of the function executes it. If another user with execute permission runs the function, nothing will be logged. After reviewing the code, this seems to be intentional:

https://github.com/pgaudit/pgaudit/blob/bd6a261f72e08daa3a5f36b46aa4b1728d23709b/pgaudit.c#L1012-L1019

Do you have any suggestions on how we might work around this limitation? Would a PR that makes the above check optional be accepted? From what I can tell, the intent was to avoid noise, but in our case, it is preventing us from logging exactly what we want to be logged.

Thanks!

**Comment by dwsteele** [comment]
pgAudit becomes incredibly noisy if you disable this functionality because every FK lookup will be logged. Also, in general logging the contents of security definer functions is not a great idea. It's usually better to just log the function call itself.

That said, we might consider a PR to disable this check. Thoughts @jconway, @sfrost?

**Comment by oschwald** [comment]
I can see foreign key queries being quite noisy. It would be nice if there was a was to exclude them without excluding security definer functions.

Re: logging the function calls, is this supported by object audit logging? When we were testing pgAudit, we tried to do that as a workaround but we were not able to get it to work. Perhaps we were doing something wrong.

**Comment by dwsteele** [comment]
> Re: logging the function calls, is this supported by object audit logging?

Is is not. This might be possible but we have not looked into it.
