### ISSUE TITLE
Installation Problem in Pg 9.4.8

### ISSUE THREAD

**Issue by lgsantosrj** [pgaudit/pgaudit#16]
Do you have a RPM package instead of compiling? I am having problems to compile on CentOS 6.8 and Pg 9.4.8. Is pgaudit available to this version of postgres?

**Comment by dwsteele** [comment]
pgaudit uses APIs that are only available in 9.5 and above.  The 2nd Quadrant version (https://github.com/2ndQuadrant/pgaudit) works on 9.4.

**Comment by lgsantosrj** [comment]
I am having some difficulties to install pgAudit on a already running PostgreSQL Server 9.4.2 on Ubuntu 14 Server.

Is it possible to provide a package so it is not necessary to compile the extension? 

By the time, Ubuntu Server is the principal and CentOS is the hot stand-by PostgreSQL Server.

Thanks in advance.

**Comment by dwsteele** [comment]
Are you trying the 2ndQuadrant version?  If so you'll need to contact them about packages.
