### ISSUE TITLE
Capability to mask sensitive data from logs

### ISSUE THREAD

**Issue by iamyogeshg** [pgaudit/pgaudit#160]
Hi,

We are looking at enabling pgaudit in our environments and we did spike on our test databases for the same. For starting purposes we have set `pgaudit.log = ALL, -FUNCTION`. 

When we create a role we can see the password always get REDACTED, which is pretty much inline with this AWS Doc https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-cleartext-logging/

Now we are looking to understand better on how to filter or possibly hide sensitive data. We understand there's various values  for pgaudit.log to filter what we want to see, but apart from this setting is there any way to tell pgaudit to REDACT some custom data in the logs? Of course we can either filter on input of logs, but we are looking for ways to modify the output as we are still trying to figure out the right level of pgaudit.log setting for our environments.

Thanks
Yogesh

**Comment by dwsteele** [comment]
There is currently no way to redact data except password as noted. In general redaction is very unreliable because small changes to queries can break it. The best way to hide data in the audit log is to use parameterized queries, which is best practice anyway to avoid SQL injection attacks.
