### ISSUE TITLE
log_rows in pgaudit

### ISSUE THREAD

**Issue by xetter9** [pgaudit/pgaudit#161]
Hi, 
I tried to configure pgaudit.log_rows=on and did SELECT & UPDATE statement, but couldn't find the logs that include the rows retrieved or affected by a statement. What else do I have to configure so that the pgaudit can log the number of records retrieved or affected by the SQL query. 

Thanks.

**Comment by dwsteele** [comment]
Are you using pgAudit 1.6.0 with PostgreSQL 14? That's the only version that has this feature.

**Comment by xetter9** [comment]
@dwsteele Noted, on the version to use log_rows settings.
