### ISSUE TITLE
Successful build but not showing Audit and session for Windows

### ISSUE THREAD

**Issue by Jan-estone** [pgaudit/pgaudit#164]
Hi, Im tried to build the pgaudit.dll based on https://github.com/pgaudit/pgaudit/issues/66 and https://www.chriswirz.com/software/pgaudit-visual-studio-compile . It was successful compile , and install, But seem like Im not getting any data and audit log from there. Even select and update also not logged .

Above is my setting. 
shared_preload_libraries = 'pgaudit'	# (change requires restart)
pgaudit.log = 'READ,WRITE,FUNCTION,ROLE,DDL,MISC,MISC_SET'
pgaudit.log_catalog = 'on'
pgaudit.log_client = 'on'
pgaudit.log_level = 'info'
pgaudit.log_parameter ='on'
pgaudit.log_relation = 'on'
pgaudit.log_statement = 'on'
pgaudit.log_statement_once = 'on'
log_line_prefix='\\%m \\%u \\%d \\%r \\%h \\%p \\%l:'
pgaudit.role = 'auditor'

**Comment by dwsteele** [comment]
`pgaudit.log_client` is generally used for debugging, as the documentation notes. `pgaudit.log_level` should also not be set.
