### ISSUE TITLE
clear text password in log by pgaudit when create user mapping options user password 

### ISSUE THREAD

**Issue by Jamespsql** [pgaudit/pgaudit#166]
pgaudit 1.5,
postgres 13.4 

pgaudit.log_catalog='on'
pgaudit.log_level='log'
pgaudit.log_parameter=on
pgaudit.log_statement_once=off
pgaudit.log='all, -misc'
pgaudit.log='ddl,role'

when create role password, or alter role password , pgaudit  works as expected and make password <REDACTED>.
but when create user mapping for postgres_fdw , clear text got audit in log by pgaudit.

CREATE USER MAPPING FOR test SERVER foreign_server OPTIONS (user 'test', password 'testfdwpass');
AUDIT: SESSION,1,1,DDL,CREATE USER MAPPING,USER MAPPING,test on server foreign_server,"CREATE USER MAPPING FOR test SERVER foreign_server OPTIONS (user 'test', password 'testfdwpass');" <<< here password is clear text instead of <REDACTED>

,

**Comment by Jamespsql** [comment]
add a control similar to create and alter role to pgaudit.c to 
  "switch (stackItem->auditEvent.commandTag)"
                   case T_CreateRoleStmt:
                case T_AlterRoleStmt:
                /* Add the case of create and alter user mapping passwords
                 * leak control  
                 */
                case T_CreateUserMappingStmt:
                case T_AlterUserMappingStmt:

**Comment by Jamespsql** [comment]
> add a control similar to create and alter role to pgaudit.c to "switch (stackItem->auditEvent.commandTag)" case T_CreateRoleStmt: case T_AlterRoleStmt: /* Add the case of create and alter user mapping passwords * leak control */ case T_CreateUserMappingStmt: case T_AlterUserMappingStmt:

this may fix the issue

**Comment by Jamespsql** [comment]
some industry need security compliance, pgaudit got used then, and password leak in audit logs need to be managed.

**Comment by dwsteele** [comment]
The best way to get a patch reviewed is to submit a PR.

**Comment by andrzejwiselka** [comment]
Are there any plans to include this for user mapping? I can see pull requests, but they are closed.

**Comment by dwsteele** [comment]
Which pull requests?

**Comment by andrzejwiselka** [comment]
https://github.com/pgaudit/pgaudit/pull/167
https://github.com/pgaudit/pgaudit/pull/168

**Comment by dwsteele** [comment]
@andrzejwiselka Looks like these were closed by the submitter.

**Comment by andrzejwiselka** [comment]
@Jamespsql, are you planning to reopen pull request?

**Comment by Jamespsql** [comment]
Andrzejwiselka,  https://github.com/pgaudit/pgaudit/pull/197 was opened

**Comment by Jamespsql** [comment]
@dwsteele, can this be merged ?
