### ISSUE TITLE
location of pgaudit log

### ISSUE THREAD

**Issue by aferrett** [pgaudit/pgaudit#17]
Is it possible to define a directory and location for the pgaudit log.  Security standards require protection of this information.  We have to allow other userids such as monitor accounts to read our server log.

**Comment by dwsteele** [comment]
PgAudit logs only to the Postgres server log.  If you have Postgres log to syslog then there are various tools you can use to split your log up.

**Comment by dwsteele** [comment]
For example, syslog-ng (https://github.com/balabit/syslog-ng) would do what you need.
