### ISSUE TITLE
Question: pgAudit html report output

### ISSUE THREAD

**Issue by julianodba** [pgaudit/pgaudit#170]
Hi, 

Can we have a nice log output report like in pgBadger by any chance?
Analysing Postgres logs is complex, annoying and boring. The bigger is the log, the worse it becomes.
Perhaps Darold could integrate a pgAudit flag in the pgBadger script, so a new pgAudit tab in the HTML reports would be cool.

Thanks in advance :)

**Comment by dwsteele** [comment]
We are not planning to get into reporting, but if you'd like to see changes to pgBadger I suggest you open an issue on that project.
