### ISSUE TITLE
Adding session variables to queries

### ISSUE THREAD

**Issue by archletekke** [pgaudit/pgaudit#171]
Hi all,

We are thinking of implementing pgaudit for monitoring our SELECT queries in the future for auditability. Is it possible to also add session variables somehow to the log so that we see the application user also in the logs in a similar way as pgMemento does it (https://github.com/pgMemento/pgMemento/wiki/User-defined-session-infos)?

Thanks in advance

**Comment by dwsteele** [comment]
I don't think this is currently possible and we are not planning any features along these lines.

If you develop a patch to add this feature then of course we'd consider it.
