### ISSUE TITLE
Question: audit connection/disconnection

### ISSUE THREAD

**Issue by fmbiete** [pgaudit/pgaudit#177]
pgaudit does not records sessions connection or disconnection.
While we have log_connections and log_disconnections in PostgreSQL core to write that information, that log it's not in pgaudit format which is kind of an incovinient.

From what I have seen the limitation in PostgreSQL is that doesn't provide hooks for pgaudit to listen in those events.
Have you discussed this limitation with PostgreSQL core team?

Adding 2 new hooks for connection and disconnect should be quite trivial, in fact I dirty added that in a matter of minutes.
What do you think of this, would it be useful to have in core, for pgaudit to use? To be honest I'm a little bit scared of going to the hacker list and dealing with all the process...

**Comment by kubo** [comment]
> From what I have seen the limitation in PostgreSQL is that doesn't provide hooks for pgaudit to listen in those events.

IMO,
* `ClientAutentication_hook` is available as connection hook. It is called almost just before `log_connection`. (https://github.com/postgres/postgres/blob/REL_14_2/src/backend/utils/init/postinit.c#L241-L258)
* `on_proc_exit()` is available to register disconnection hook. `log_disconnection` uses it. (https://github.com/postgres/postgres/blob/REL_14_2/src/backend/tcop/postgres.c#L4108-L4109)
