### ISSUE TITLE
PgAudit is logging Delete Statements as well with READ class (Select)

### ISSUE THREAD

**Issue by makert40** [pgaudit/pgaudit#179]
I had setup pgaudit on one of our instances to test auditing of SELECT statements only for some specific tables and turns out that instead of logging audit trails for SELECTs only, it audits DELETEs as well.
I went through different documentation to make sure my statements were correct and they were all OK. 

As explained, the below commands enables auditing for SELECT statements on test_table but it also produces audit trails for DELETE at the same time. 

CREATE EXTENSION pgaudit;
CREATE ROLE rds_pgaudit;
GRANT SELECT ON test_table TO rds_pgaudit;

We have conducted few tests and here are the results. 

If we issue DELETE statements with a SELECT embedded on it, we get them logged (which is NOT what we want). Irrespectively if within the inner SELECT has the table/view's name on it.
The below statements all got logged in the auditing trail.

delete from test_table where 1=0 and entry_id in (select 123456789);

delete from test_table where 1=0 and trans_id in (select trans_id from test_table where entry_id=123456789);

delete from test_table where 1=0 and trans_id in (select trans_id as acc$ from test_table where entry_id=123456789);

DELETE FROM test_table WHERE rx_m_row$ IN ( SELECT UNNEST($1));

If we issue DELETEs with NO SELECT word anywhere within the statement, then the same is NOT logged, even if they have a where clause, like the below:
i.e: delete from test_table where 1=0;

This behaviour suggests me pgaudit will do something similar to "grep -i 'select' $query_statement" within the statement rather than analysing it from the initial word of the statement, like "grep -i '^select' $query_statement", thus logging any statement which has the word SELECT anywhere within the statement.
Our tests were done onto 2 different databases to ensure the issue is consistent and the same issue repeats on both databases.

That said, would you know if there's anything we could do in order to make it work as it should?

**Comment by dwsteele** [comment]
It'd be helpful to see the audit log produced, but in general this sounds correct to me. There is a select, so it will be logged. We don't analyze the statement ourselves, we rely on Postgres to tell us which statement types are present. Even if we could, there is still a select on that table in there, which means the statement needs to be audited.

The reason for this is that a user could use `RETURNING FROM` to extract data from the table even during a delete.
