### ISSUE TITLE
Is fine grain/conditional  auditing possible in Postgres?

### ISSUE THREAD

**Issue by Shrd99** [pgaudit/pgaudit#182]
Hi Team,

Could you please help me with details that if we want to customise Auditing in Postges is that possible. For eg. If i want to Audit only specific Statements for specific users/role is that possible to customise the auditing configuration so that we can only audit specific queries and for specific user/policy/role?

to be further explain :
Just like we have fine grained auditing available in Oracle where we can audit objects based on some policies and can monitor data access based on content. Using policies, you can specify the columns and conditions that you want audit records for. Conditions can include limiting the audit to specific types of DML statements used in connection with the columns that you specify.

This kind of filtering we are looking for where we can audit specific DDL and DML statement for specific user etc.

Regards,
Shruti Dixit

**Comment by dwsteele** [comment]
You should be able to do most of what you are asking for with object auditing. Separate audit roles can be created and assigned to users with `alter user set 'pgaudit.role=xxx'`. See https://github.com/pgaudit/pgaudit#object-audit-logging.
