### ISSUE TITLE
compile error....

### ISSUE THREAD

**Issue by longforrich** [pgaudit/pgaudit#183]
I want to using this for greenplum7 which is postgreSQL 12,but.........
pgaudit.c:540:24: error: this statement may fall through [-Werror=implicit-fallthrough=]
                     if (stackItem->auditEvent.commandText != NULL)

The gcc cmdline is 
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -g -O0  -Werror=uninitialized -Werror=implicit-function-declaration -fPIC -I. -I. -I../../src/include   -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgaudit.o pgaudit.c -MMD -MP -MF .deps/pgaudit.Po

It's generated by greenplum

The gcc is
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

I see line 590 in pgaudit.c
/* Fall through */

so..Is this intended to "fall through"?

adding the following line to Makefile, and it works
override CFLAGS := $(filter-out -Werror=implicit-fallthrough=3, $(CFLAGS))

but, is that the right thing to do? 
or..shall we need to change the code of 'swith'? I guess.

thx!

**Comment by dwsteele** [comment]
> so..Is this intended to "fall through"?

Yes.

> but, is that the right thing to do?

Ignore, or don't compile with `-Werror`. Unfortunately this warning is rather dumb, but I can't see any reason to change correct code to make it happy.

**Comment by longforrich** [comment]
ok! Thank for questions，It's enough for my work.
