### ISSUE TITLE
pgaudit running without creating the extension

### ISSUE THREAD

**Issue by thecloudengineer** [pgaudit/pgaudit#184]
Hi Team,

I have experienced some peculiar behavior and I was hoping you could give me an explanation as to why this is happening.
I add pgaudit to my shared_preload_libraries and set pgaudit.log =all, I never CREATE the extension yet pgaudit is somehow running and logging as if I did. 

For conext, when I check for the extension on my database I see the following:

=============================================================
>postgres=> select * from pg_available_extensions where name like '%pgaudit%';
  name   | default_version | installed_version |             comment
---------+-----------------+-------------------+---------------------------------
 pgaudit | 1.5.1           |                   | provides auditing functionality
(1 row)

>postgres=> select name,setting from pg_settings where (name ='shared_preload_libraries' or name like 'pgaudit%') order by name desc;
            name            |               setting
----------------------------+-------------------------------------
 shared_preload_libraries   | pg_stat_statements,pgaudit
 pgaudit.role               |
 pgaudit.log_statement_once | off
 pgaudit.log_relation       | off
 pgaudit.log_parameter      | off
 pgaudit.log_level          | log
 pgaudit.log_client         | off
 pgaudit.log_catalog        | on
 pgaudit.log                | all
(9 rows)

=============================================================

I then run:
>postgres=> select count(*) from pgbench_tellers;
 count
-------+
   500
(1 row)

>postgres=> select count(*) from pgbench_tellers;
 count
-------+
   500
(1 row)

Yet I see this in my logs:

>2022-05-18T15:54:16.000+02:002022-05-18 13:54:16 UTC:172.31.30.176(39400):postgres@postgres:[17505]:LOG: AUDIT: SESSION,2,1,READ,SELECT,,,select count(*) from pgbench_tellers;,<not logged>

Could anyone explain to me how this is possible and why it is happening?

**Comment by dwsteele** [comment]
Yes, it will run if it is in `shared_preload_libraries`. The extension just allows it to provide extra detail. PR #175 adds some info the docs about this.
