### ISSUE TITLE
No logging option for bytea columns 

### ISSUE THREAD

**Issue by JMLessard** [pgaudit/pgaudit#186]
Logging the bytea columns bloat the log file and affects performance by adding more disk writes.
I am wondering if there is a way to not log the bytea column value from insert and update when pgaudit.log_parameter is enabled?
There doesn't seem to be a parameter like pgaudit.log_parameter=nobytea.

**Comment by dwsteele** [comment]
This is likely possible but might slow down auditing so it might need a separate setting.

We'd he happy to review a patch to add this functionality.

**Comment by JMLessard** [comment]
Unfortunatly I do not have time but how much will it be to get a patch?

**Comment by sfrost** [comment]
While we're interested in adding this capability, unfortunately at this time we don't really have time to put into this ourselves.  As David mentioned, we'd be willing to spend time reviewing a patch to add this functionality should one be produced.
