### ISSUE TITLE
Postgresql 14.4 + pgaudit 16.2 failing make check: missing /share/extension/pg_stat_statements.control

### ISSUE THREAD

**Issue by lfsm** [pgaudit/pgaudit#187]
Compiled from source on CentOS Linux release 7.9.2009 (Core) postgresql 14.4 and pgaudit 16.2 .

When running the pgaudit "make check" I get the error:

/postgresql-14.4/contrib/pgaudit/pgaudit.conf --dbname=contrib_regression pgaudit
============== removing existing temp instance        ==============
============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============
running on port 58084 with PID 56950
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test pgaudit                      ... FAILED      360 ms
============== shutting down postmaster               ==============

======================
 1 of 1 tests failed.
======================

The differences that caused some tests to fail can be viewed in the
file "/postgresql/basedir/packages/postgresql-14.4/build_dir/contrib/pgaudit/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/postgresql/basedir/packages/postgresql-14.4/build_dir/contrib/pgaudit/regression.out".

cat "/postgresql/basedir/packages/postgresql-14.4/build_dir/contrib/pgaudit/regression.diffs"
diff -U3 /postgresql/basedir/packages/postgresql-14.4/contrib/pgaudit/expected/pgaudit.out /postgresql/basedir/packages/postgresql-14.4/build_dir/contrib/pgaudit/results/pgaudit.out
--- /postgresql/basedir/packages/postgresql-14.4/contrib/pgaudit/expected/pgaudit.out   2022-02-25 21:00:56.000000000 +0000
+++ /postgresql/basedir/packages/postgresql-14.4/build_dir/contrib/pgaudit/results/pgaudit.out  2022-06-23 12:49:29.882072374 +0100
@@ -2507,11 +2507,12 @@
 SET pgaudit.log_level = 'warning';
 CREATE EXTENSION pg_stat_statements;
 WARNING:  AUDIT: SESSION,3,1,DDL,CREATE EXTENSION,,,CREATE EXTENSION pg_stat_statements;,<not logged>
+ERROR:  could not open extension control file "/postgresql/basedir/packages/postgresql-14.4/build_dir/tmp_install/postgresql/basedir/pgsql_14.4/share/extension/pg_stat_statements.control": No such file or directory
 ALTER EXTENSION pg_stat_statements UPDATE TO '1.9';
 WARNING:  AUDIT: SESSION,4,1,DDL,ALTER EXTENSION,,,ALTER EXTENSION pg_stat_statements UPDATE TO '1.9';,<not logged>
-NOTICE:  version "1.9" of extension "pg_stat_statements" is already installed
+ERROR:  extension "pg_stat_statements" does not exist
 DROP EXTENSION pg_stat_statements;
-WARNING:  AUDIT: SESSION,5,1,DDL,DROP EXTENSION,,,DROP EXTENSION pg_stat_statements;,<not logged>
+ERROR:  extension "pg_stat_statements" does not exist
 SET pgaudit.log_level = 'notice';
 -- Cleanup
 -- Set client_min_messages up to warning to avoid noise

From what I can see, a create extension was added to the test file ( from pgaudit version 16.1 ), but in my case it seems the temporary postgresql cluster that is instantiated for the "make check" does not have/ cannot find all the necessary files.

**Comment by dwsteele** [comment]
Here's the error:
```
ERROR: extension "pg_stat_statements" does not exist
```
The regression tests require contrib to be installed for extension tests.

**Comment by lfsm** [comment]
Then what am I missing? I am building PostgreSQL from source ( make all; make world;), building the extensions. I have the dir pgaudit under the contrib dir, where I run make for pgaudit, it compiles successfully. But then I do the "make check" and the script that creates the temporary postgresql cluster fails to copy the extension files. They do exist, they were compiled on the "make world" step.

**Comment by dwsteele** [comment]
I'm not sure because we do not test or develop under a source tree. See https://github.com/pgaudit/pgaudit/tree/master/test for our test environment using PGXS.
