### ISSUE TITLE
pgaudit not masking/REDACTING password for error statement

### ISSUE THREAD

**Issue by govindkailas** [pgaudit/pgaudit#189]
I am trying to cover a scenario where passwords should be masked even for the error statement. I have deployed a helm chart with pgaudit set to `role`, 
`helm install psql-pass-test --set audit.pgAuditLog='role' bitnami/postgresql`

I ran a create user statement twice and in the second attempt it showed the password instead of showing `<REDACTED>`
Below are the logs, 

`CREATE USER test1 WITH PASSWORD 'test1';` 

`2022-06-30 09:38:05.108 GMT [210] LOG:  AUDIT: SESSION,1,1,ROLE,CREATE ROLE,,,CREATE USER test1 WITH PASSWORD <REDACTED>,<not logged>` --- expected and happy with this 💯 

Ran the same once again, `CREATE USER test1 WITH PASSWORD 'test1';`

`2022-06-30 09:38:29.653 GMT [210] ERROR:  role "test1" already exists
2022-06-30 09:38:29.653 GMT [210] STATEMENT:  CREATE USER test1 WITH PASSWORD 'test1';`  -- Now for the error statement its showing password. What should I do to REDACT the passwords in error statements as well?

**Comment by dwsteele** [comment]
This statement was *not* logged by pgaudit:
```
2022-06-30 09:38:29.653 GMT [210] ERROR: role "test1" already exists 2022-06-30 09:38:29.653 GMT [210] STATEMENT: CREATE USER test1 WITH PASSWORD 'test1';
```
Notice that it does not contain `AUDIT`.

I believe you can use log_error_verbosity and log_min_error_statement to control when statements will be output, but as far as I know there is no way to redact them. This is strictly a PostgreSQL logging issue and is not related to pgAudit.
