### ISSUE TITLE
pgaudit_analyze --daemon when started via ssh doesn't complete

### ISSUE THREAD

**Issue by crunchyjohn** [pgaudit/pgaudit#19]
There is a little bit of strange behavior with the pgaudit_analyze script when:
a) it is started up with the --daemon option via ssh from another machine and
b) it is using a fast ssh connection

The problem happens when pgaudit_analyze is invoked in such a way:
ssh -t <server> 'sudo /usr/bin/pgaudit_analyze --daemon /var/lib/pgsql/9.5/data/pg_log --user=postgres

If the ssh connection is slow, the above command will work perfectly to spawn an analyzer process that will stay up on the remote machine.  However, if ssh is really fast, the command will complete with a success error code, but the analyzer fails to start.

This can be worked around as follows:
ssh -t -t <server> 'sudo /usr/bin/pgaudit_analyze --daemon /var/lib/pgsql/9.5/data/pg_log --user=postgres && sleep 1

It looks like the pgaudit_analyze process is saying it's completed before it's 100% up and running.  If I were to guess, this could be because of a 'fork' call that happens in the --daemon process that is not yet finished.  But, that's just an off-the-wall guess.

This may be a minor edge case, but I thought it worth logging.

**Comment by dwsteele** [comment]
I agree, it's definitely worth looking into.  I'll let you know when I figure out what's going on.

**Comment by dwsteele** [comment]
I had a look at this and I don't see how else the process could be daemonized.  It happens as late as I think it practical.

Given that this is not a standard usage and there have been no field reports I'm going to close this issue.
