### ISSUE TITLE
pgaudit has no update path from version "1.2.3" to version "1.4.2" 

### ISSUE THREAD

**Issue by pnjha** [pgaudit/pgaudit#191]
We are using AWS RDS PostgreSQL instance where the following command fails
`ALTER EXTENSION "pgaudit" UPDATE TO '1.4.2';` 
with error: 
`"pgaudit" has no update path from version "1.2.3" to version "1.4.2"`
I saw a similar issue been raised earlier here: https://github.com/pgaudit/pgaudit/issues/155
I wanted to check what is the status of this.

**Comment by khaledghazy22** [comment]
solution for this problem 
drop extension pgaudit ;
then create it again
create extension pgaudit ;
