### ISSUE TITLE
pgaudit 1.7 stable release plan?

### ISSUE THREAD

**Issue by capri1989** [pgaudit/pgaudit#193]
Hey,

I wasn't sure where to ask this question but I couldn't find a mailing list or a forum/group to ask this.

Do you already have a schedule for a 1.7 stable release after PostgreSQL 15 GA?
Just curious how the stable release usually works after a new GA version of PostgreSQL.

Thanks a lot,
Kai

**Comment by dwsteele** [comment]
We like to wait until the GA release is close in case there are any last-minute changes that affect pgAudit. This is pretty unlikely but there is no benefit to releasing too early.

pgAudit 1.7.0 has now been released.
