### ISSUE TITLE
upgrade pgaudit from 1.5.0 to 1.5.2 resulted in security issues (SECURITY_TYPE=DEFINER)

### ISSUE THREAD

**Issue by giacomobonafe** [pgaudit/pgaudit#194]
Hello,
we observe that the following routines have been installed as part of the pgaudit v1.5.2 extension

postgres=# select * from information_schema.routines where specific_schema!='pg_catalog' and routine_type='FUNCTION' and security_type!='INVOKER';
specific_catalog | specific_schema | specific_name | routine_catalog | routine_schema | routine_name | routine_type | mod>
------------------+-----------------+-------------------------------+-----------------+----------------+-------------------------+--------------+---->
postgres | public | pgaudit_ddl_command_end_56101 | postgres | public | pgaudit_ddl_command_end | FUNCTION | >
postgres | public | pgaudit_sql_drop_56103 | postgres | public | pgaudit_sql_drop | FUNCTION | >
(2 rows)

they reflect in tripwire as a security issue because they have been created with SECURITY_TYPE=DEFINER.

how can we solve this issue other than downgrade to pgaudit v1.5.0 on PostgreSQL 13.9.

thanks and regards
giacomo

**Comment by dwsteele** [comment]
This was updated in 881c617084 as a result of some security concerns. Can you explain why you thing this is an issue?

**Comment by giacomobonafe** [comment]
This alert is triggered by tripwire that you use to lock down postgres. The question is can we revoke DEFINER as SECURITY_TYPE from those two functions without compromising the overall behaviour of the pgaudit extension ?



From Tripwire check:

To remediate failure of this policy test, revoke excessive privileges on functions.

Revoking excessive privileges on functions:

Become superuser or assume an equivalent role.

Run the following query to list functions has SECURITY DEFINER:

SELECT nspname, proname, proargtypes, prosecdef, rolname, proconfig 
FROM pg_proc p 
JOIN pg_namespace n ON p.pronamespace = n.oid 
JOIN pg_authid a ON a.oid = p.proowner 
WHERE prosecdef = 'true' OR NOT proconfig IS NULL;



Review list of function above and determine which functions need to be revoked SECURITY DEFINER.
Change a SECURITY DEFINER function to others, for example SECURITY INVOKER, using the following query:




ALTER FUNCTION <functionname> SECURITY INVOKER;
If it is not possible to revoke SECURITY DEFINER, please check this test manualy. 
Ensure that the function can be executed by only the accounts that absolutely need such functionality.:
Run the following query to list roles are granted to execute functions:

SELECT proname, proacl FROM pg_proc WHERE proname = 'pgaudit_ddl_command_end';

Revoke execute on this function using the query:
REVOKE EXECUTE ON FUNCTION <functionname> FROM <user|role>;

**Comment by dwsteele** [comment]
>  The question is can we revoke DEFINER as SECURITY_TYPE from those two functions without compromising the overall behaviour of the pgaudit extension ?

Perhaps. I wouldn't try it, though.

We have tested using these options -- from our perspective the behavior with other options is undefined.
