### ISSUE TITLE
Does pgaudit.log_parameter only work with prepared statements?

### ISSUE THREAD

**Issue by manosntoulias** [pgaudit/pgaudit#196]
> **PARAMETER** - If pgaudit.log_parameter is set then this field will contain the statement parameters as quoted CSV or <none> if there are no parameters. Otherwise, the field is 'not logged'.

Could the 'statement parameters' in the sentence above be referring to something else other than prepared statements? I am using Dbeaver so originally I confused the :parameter syntax that Dbeaver uses in queries would be enough but it is not the case.

I am asking because I'll have to change all my queries to prepared statements if there is no other way.

Thanks

**Comment by kubo** [comment]
> Could the 'statement parameters' in the sentence above be referring to something else other than prepared statements? 

Yes when the parameters are sent to the server separately such as parameters send by [PQexecParams] in libpq and [psycopg3]'s [server-side binding].

No when they are replaced with parameter values at the client side before they are sent to the server such as [psycopg2] does.

[PQexecParams]: https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXECPARAMS
[server-side binding]: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding
[psycopg2]: https://www.psycopg.org/docs/
[psycopg3]: https://www.psycopg.org/psycopg3/docs/

> I confused the :parameter syntax that Dbeaver uses in queries

DBeaver replaces parameters at the client side. See https://github.com/dbeaver/dbeaver/issues/15310.

**Comment by dwsteele** [comment]
Thanks for the answer @kubo!
