### ISSUE TITLE
Streaming the AUDIT: records?

### ISSUE THREAD

**Issue by beejones** [pgaudit/pgaudit#199]
Is it possible to stream the AUDIT: records?  I want external processes to subscribe to pgaudit and get the latest pgaudit record?
A possible solution would be to send a notification with the audit record as content.
Is such streaming solution existing or planned for pgaudit?
Thanks

**Comment by dwsteele** [comment]
Nothing like this is planned. You can direct the Postgres logs to another system by logging with syslog -- there may be something you can do with that.
