### ISSUE TITLE
9.6 regression tests

### ISSUE THREAD

**Issue by disco-stu** [pgaudit/pgaudit#20]
While working on a debian package for pgAudit I ran the regressions tests against PostgreSQL 9.6 (the current version contained in Debian stretch). Some of the tests failed. The corresponding diff is attached ([regression.diffs.txt](https://github.com/pgaudit/pgaudit/files/578468/regression.diffs.txt)).

Please let me know if you need further information.

regards,
 - Adrian

**Comment by dwsteele** [comment]
Hi Adrian,

This is a known issue - I have the fixes on a branch but have not had the time to merge them in yet since I also want to fork off the pgaudit_analyze project into a new repo as well.

I'll be doing this work in the next week and will make sure what I'm seeing matches the patch you sent.

**Comment by disco-stu** [comment]
Hi David,

thanks for the quick reply. Ok, will hold back the package then. Currently the source package provides 1+N binary packages (pgaudit_analyze) and one extension package for each "supported" version.

**Comment by dwsteele** [comment]
Hi Adrian,

081f5e3722ea19112c3d322573480e94ab6068a4 is the release candidate for 9.6.  It won't be tagged until QA has finished testing but you can start get started with that if you like.
