### ISSUE TITLE
clear text password in postgres log while creating pglogical node

### ISSUE THREAD

**Issue by Viralshah009** [pgaudit/pgaudit#201]
When I try to create my publisher/subscriber node using pglogical, pgaudit seem to not redact password that i have to pass in my select string. Can this be addressed? I tried looking online if someone has done it but couldn't find a solution.

`db=#  SELECT pglogical.create_node(
    node_name := 'subcriber_node',
    dsn := 'host=192.10.1.10 port=5432 dbname=pub_db user=abc password=abc');
`

Following is what I see in my logs:

`
< 2023-01-25 21:05:31.564 EST pid=[10981-7], db=db, user=abc, app=psql, rhost=::1, tid=11/2563 > LOG:  AUDIT: SESSION,2,1,READ,SELECT,,,"SELECT pglogical.create_node(
	    node_name := 'subscriber_node',
	    dsn := 'host=192.10.1.10 port=5432 dbname=db user=abc password=abc');",<not logged>
`
I am using PostgreSQL 14.5

**Comment by thiagosantosleite** [comment]
Would be nice to have a proper solution for it, I have the same issue currently.
