### ISSUE TITLE
Not getting log using pgaudit

### ISSUE THREAD

**Issue by AnujiVarghese** [pgaudit/pgaudit#206]
Hi,
I am using PostgreSQL 13.7 and followed the below steps in DBeaver.

set pgaudit.log = 'ALL'
set pgaudit.log_catalog = on
set pgaudit.log_client = off
set pgaudit.log_level = log
set pgaudit.log_parameter = off
set pgaudit.log_relation = on
set pgaudit.log_statement_once = on

create table test(x int);
create view test_view as select * from test;
select * from test_view;

Not getting log using pgaudit. How can i view the log details?

**Comment by althaf004** [comment]
try with 

set pgaudit.log_level = notice;
