### ISSUE TITLE
Audit log csv by pgaudit version 1.6.2 has 3 extra columns

### ISSUE THREAD

**Issue by meiravRath** [pgaudit/pgaudit#211]
Hi,

My name is Meirav, I work at Imperva, we have an audit log collector and analyzer which supports audit logs created by pgaudit as it's used in AWS. 
I have a customer support case in which their Aurora PostgreSQL version 14.6 instances creates an audit log that our log analyzer cannot parse - the csv file has 3 extra columns at the end. It turns out that starting from Aurora/PostgreSQL versions 14.6, AWS are using pgaudit version 1.6.2. 
I looked at version 1.6.2's changelog [here ](https://github.com/pgaudit/pgaudit/releases/tag/1.6.2) and I don't see any reference to why this could have happened.

Can anyone shed some light on this issue?
You can contact me here or email me directly at meirav.rath@imperva.com

Thanks

**Comment by mbanck** [comment]
This sounds like a question to be directed at AWS/Aurora, did you try to ask them?

**Comment by meiravRath** [comment]
Ha, it took AWS only three days to throw the blame onto someone else (in this case, pgaudit).
To directly quote the technical support person on the ticket I opened to them:
"After deep diving into a thorough investigation, our internal team have concluded that there is no issue on the AWS side nor with the
 infrastructure; this issue with additional columns is an update that was implemented by PostgreSQL community release. Thus, we are humbly asking if you can please modify/update your log collector to make it compatible with PostgreSQL 14.x, because unfortunately
 this change that was implemented by PostgreSQL community release is not in our control. "

So, I guess this question isn't directed at them.

**Comment by mbanck** [comment]
I guess it would help if you could provide (possibly anonymized) samples of the logs in question, best with before/after

**Comment by meiravRath** [comment]
Sure thing, you can find them [here](https://github.com/meiravRath/pgaudit_csv_issue). These are csvs the escalation engineer responsible for this case generated while trying to recreate and debug this issue. One has been generated by pgaudit on Aurora PostgreSQL 12.x and the other on Aurora PostgreSQL 14.6.

**Comment by dwsteele** [comment]
The only one I can find since PG12 is e8cded51a so I'm not sure how you could be getting three extra fields. Anyway, this is something to take up with Amazon. They might be running a modified version of pgAudit.

**Comment by meiravRath** [comment]
Look earlier in this issue, I did take this up with AWS, they say its the pg community.

**Comment by dwsteele** [comment]
To be clear, the community does not provide support for AWS products. You are welcome to look through the commit history, but there is always the chance that AWS modified the code and there's no way for us to know. As far as I can see, only one (optional) field has been added since PG12. If you are seeing more then there is nothing we can do, as AWS is closed source and proprietary.

**Comment by meiravRath** [comment]
The change did not start in PG12, as you can see from the example logs, it started in PG14.

I'm also not sure why it is down to me to search your code. I am a developer at a business collaborator of one of your customers, I have my own code responsibilities in the company where I work. Should I find a bug in the functions of one of our teams' products, that team is the one responsible for changing the code to fix the bug. 
Those three extra columns are empty and if no one can think of a purpose for adding them, it is an indication that this is a bug.

As much as I understand software giants like AWS, if a small piece of software they use starts to malfunction and hurt their customers while refusing to even search their own code to find the possible cause of the problem, that small piece of software gets replaced very quickly.

**Comment by dwsteele** [comment]
> I'm also not sure why it is down to me to search your code.

That's pretty much how open source works. You have not shown there is any issue in the open source code and everything appears to be operating as expected on our end.

> I am a developer at a business collaborator of one of your customers

AWS is not a customer. They use the pgAudit extension for free, which is completely fine since it is open source.

> that small piece of software gets replaced very quickly

AWS is welcome to use whatever audit software they prefer.
