### ISSUE TITLE
password visible during create user and grant role simultaneously via pgadmin

### ISSUE THREAD

**Issue by maheshwc** [pgaudit/pgaudit#214]
We have found a bug which allows pgaudit extension in postgres engine to show password while creating user when pgaudit is enabled in database.

Below are the steps to replicate.

<img width="824" alt="Screenshot 2023-05-23 at 3 34 17 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/a4a85fa6-ddc1-49f7-9a71-1925a221ff53">
<img width="725" alt="Screenshot 2023-05-23 at 3 35 03 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/5441273b-da07-4361-bd4f-4db1aeb9a0ee">
<img width="725" alt="Screenshot 2023-05-23 at 3 35 09 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/e003c332-9222-4d80-bcbf-2a8e58979e56">
<img width="725" alt="Screenshot 2023-05-23 at 3 35 17 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/efa93d8d-058f-47d3-8e2f-66d78ca9d72d">
<img width="725" alt="Screenshot 2023-05-23 at 3 37 22 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/0452e05a-f722-4900-8183-c439edcf2f47">
<img width="725" alt="Screenshot 2023-05-23 at 3 37 26 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/09b5b8e6-8f49-4bbe-bd7b-f2f7f3de47f4">

<img width="956" alt="Screenshot 2023-05-23 at 3 38 06 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/f2962512-69f7-4e51-97c6-bd4f469e07c1">

It seems when PGAdmin is passing/executing 2 SQL queries(Create User and Grant role) together , postgress engine is unable to encrypt password as REDACTED.

**Comment by dwsteele** [comment]
Looks like Postgres is telling pgAudit that this entire statement is a grant so we don't even try to do any redaction. I'm not sure if there is anything we can do about this as we don't control the parser.

We have noticed this before and it is arguably a bug in Postgres, though it seems like one that is unlikely to be fixed. I can't remember the reasons anymore but we have brought this up in the past. 

In particular this is a nightmare for extension scripts that can be quite large. In that case we suppress the script but I doubt that will work here.

Is there a CREATE ROLE audit record further up with the password redacted?

**Comment by maheshwc** [comment]
No, there is no CREATE ROLE audit record further up with the password redacted.

**Comment by dwsteele** [comment]
What are your pgaudit settings?

**Comment by maheshwc** [comment]
<img width="908" alt="Screenshot 2023-06-13 at 4 03 47 PM" src="https://github.com/pgaudit/pgaudit/assets/134497018/041cbd14-1751-439d-ba27-2b7fc4db7ab2">

@dwsteele  : Apologies. Replicated the scenario again for the question asked.  CREATE ROLE audit record further up with the password redacted.

**Comment by dwsteele** [comment]
Yeah, that's what I expected. And there's pretty much nothing we can do about. That's the command string Postgres gives us, even though it does get broken up in the parser.

**Comment by nachoalonsoportillo** [comment]
@dwsteele You could use pstmt->stmt_location & stmt_len to focus on the text of interest for the statement that you're processing, rather than working on queryString as a whole.

The way it is being done creates odd entries, like when you run the following batch, if you happen to be logging `READ`and `ROLE`:

```
create user oneuser password 'pwdforoneuser';
select 1;
create user otheruser password 'pwdforotheruser';
```

in which case it reports the following three entries:

```
create user oneuser password <REDACTED>
```
```
create user oneuser password 'pwdforoneuser';
select 1;
create user otheruser password 'pwdforotheruser';
```
```
create user oneuser password <REDACTED>
```

Notice that the third entry is referring to the first statement, because that's the first place where it finds the magic "password" keyword.

Things can get worse if you put comments that include the word "password" preceeding all three instructions.

**Comment by nachoalonsoportillo** [comment]
Also, for figuring out where exactly the password is located, you would better use [this technique ](https://github.com/postgres/postgres/blob/bea97cd02ebb347ab469b78673c2b33a72109669/src/backend/commands/user.c#L191).

For the following batch:

```
drop user abc;
create user abc with password 'ffff';
select * from t1;
```


When your hook is called for the second statement, you get this:

```
((postgres!PlannedStmt *)0x2134a592210)                 : 0x2134a592210 [Type: PlannedStmt *]
    [+0x000] type             : T_PlannedStmt (309) [Type: NodeTag]
    [+0x004] commandType      : CMD_UTILITY (6) [Type: CmdType]
    [+0x008] queryId          : 0x9a25bace25f7625e [Type: unsigned __int64]
    [+0x010] hasReturning     : false [Type: bool]
    [+0x011] hasModifyingCTE  : false [Type: bool]
    [+0x012] canSetTag        : true [Type: bool]
    [+0x013] transientPlan    : false [Type: bool]
    [+0x014] dependsOnRole    : false [Type: bool]
    [+0x015] parallelModeNeeded : false [Type: bool]
    [+0x018] jitFlags         : 0 [Type: int]
    [+0x020] planTree         : 0x0 [Type: Plan *]
    [+0x028] rtable           : 0x0 [Type: List *]
    [+0x030] permInfos        : 0x0 [Type: List *]
    [+0x038] resultRelations  : 0x0 [Type: List *]
    [+0x040] appendRelations  : 0x0 [Type: List *]
    [+0x048] subplans         : 0x0 [Type: List *]
    [+0x050] rewindPlanIDs    : 0x0 [Type: Bitmapset *]
    [+0x058] rowMarks         : 0x0 [Type: List *]
    [+0x060] relationOids     : 0x0 [Type: List *]
    [+0x068] invalItems       : 0x0 [Type: List *]
    [+0x070] paramExecTypes   : 0x0 [Type: List *]
    [+0x078] utilityStmt      : 0x2134a59ee90 [Type: Node *] <<<===
    [+0x080] stmt_location    : 14 [Type: int] <<<<<<---------
    [+0x084] stmt_len         : 37 [Type: int] <<<<<<---------


dt postgres!CreateRoleStmt 0x2134a59ee90
   +0x000 type             : a6 ( T_CreateRoleStmt )
   +0x004 stmt_type        : 1 ( ROLESTMT_USER )
   +0x008 role             : 0x00000213`4a59edc8  "abc"
   +0x010 options          : 0x00000213`4a59ee48 List <<<===


dx -r1 ((postgres!List *)0x2134a59ee48)
((postgres!List *)0x2134a59ee48)                 : 0x2134a59ee48 [Type: List *]
    [+0x000] type             : T_List (1) [Type: NodeTag]
    [+0x004] length           : 1 [Type: int]
    [+0x008] max_length       : 5 [Type: int]
    [+0x010] elements         : 0x2134a59ee60 [Type: ListCell *] <<<===
    [+0x018] initial_elements [Type: ListCell [0]]


dx -r1 ((postgres!ListCell *)0x2134a59ee60)
((postgres!ListCell *)0x2134a59ee60)                 : 0x2134a59ee60 [Type: ListCell *]
    [+0x000] ptr_value        : 0x2134a59ee00 [Type: void *] <<<===
    [+0x000] int_value        : 1247407616 [Type: int]
    [+0x000] oid_value        : 0x4a59ee00 [Type: unsigned int]
    [+0x000] xid_value        : 0x4a59ee00 [Type: unsigned int]


dt postgres!DefElem 0x2134a59ee00
   +0x000 type             : 54 ( T_DefElem )
   +0x008 defnamespace     : (null) 
   +0x010 defname          : 0x00007ff6`3e4ea170  "password" <<<===
   +0x018 arg              : 0x00000213`4a59ede8 Node <<<===
   +0x020 defaction        : 0 ( DEFELEM_UNSPEC )
   +0x024 location         : 0n36 <<<******<<<****** Here's the location of the password


dx -r1 ((postgres!Node *)0x2134a59ede8)
((postgres!Node *)0x2134a59ede8)                 : 0x2134a59ede8 [Type: Node *]
    [+0x000] type             : T_String (444) [Type: NodeTag]


dt postgres!String 0x00000213`4a59ede8
   +0x000 type             : 1bc ( T_String )
   +0x008 sval             : 0x00000213`4a59edd8  "ffff"
```

**Comment by dwsteele** [comment]
> You could use pstmt->stmt_location & stmt_len to focus on the text of interest for the statement that you're processing, rather than working on queryString as a whole.

This would require scrutiny of pretty much every statement that comes through and I rather doubt the additional overhead would be worth it to most users.

There are plenty of ways that a password can sneak into the logs and trying to catch all of them is like playing whack-a-mole. To some extent I regret the limited redactions that we do have as they give the impression that this is a problem we are trying to solve.

**Comment by anarazel** [comment]
It may be worth noting that logging the whole statement from within a utility hook isn't a great idea independent of passwords:
https://github.com/postgres/postgres/blob/e51c2a46b54ee294c699499bedf76940ce2f392c/src/backend/tcop/utility.c#L489-L496

**Comment by nachoalonsoportillo** [comment]
For reference, this is how pg_stat_statements does it https://github.com/postgres/postgres/blob/b7d35d393edbe2d4333dde81496e8a362abc85bd/contrib/pg_stat_statements/pg_stat_statements.c#L861

**Comment by dwsteele** [comment]
@nachoalonsoportillo I misunderstood your intent, so my apologies for that. You and @anarazel are correct that this is a better way to log overall, regardless of password redaction.

I was a bit curious as to why this did not make it into the original implementation but it turns out primary development of pgAudit was done before these field existed. Better late than never, I suppose.

Even so -- it's weird that stmt_len is sometimes not set. In those cases we just use the entire statement but it kind of feels like a bug in PostgreSQL.

I have created a WIP patch in #241.

**Comment by nachoalonsoportillo** [comment]
@dwsteele Thanks for revisiting this and thanks for implementing the fix.

BTW, have you also revisited my other suggestion which you responded with in [this comment](https://github.com/pgaudit/pgaudit/issues/214#issuecomment-2068340562)?

What I was suggesting wasn't to scrutinize every single statement the hook is called for. I was just suggesting to replace the current logic used to locate the password token in CREATE/ALTER USER|ROLE statements, with one more precise and accurate in determining the actual location of that token, as determined by the parser.

**Comment by anarazel** [comment]
> Even so -- it's weird that stmt_len is sometimes not set. In those cases we just use the entire statement but it kind of feels like a bug in PostgreSQL.

This is explicitly documented:
```
	ParseLoc	stmt_len;		/* length in bytes; 0 means "rest of string" */
```

**Comment by anarazel** [comment]
@dwsteele 
> Even so -- it's weird that stmt_len is sometimes not set. In those cases we just use the entire statement but it kind of feels like a bug in PostgreSQL.

0 is explicitly documented to be the whole string;
```
	ParseLoc	stmt_len;		/* length in bytes; 0 means "rest of string" */
```

**Comment by dwsteele** [comment]
> BTW, have you also revisited my other suggestion which you responded with in https://github.com/pgaudit/pgaudit/issues/214#issuecomment-2068340562?

I agree this could potentially improve the output in this case but it is not something I am planning on working on. There are lots of ways password can sneak into the log and trying to find them all is like playing whack-a-mole.

That said, if you or somebody else submits a patch that makes this particular case better (even if it ignores other cases) there's a fair chance it would be committed.

**Comment by dwsteele** [comment]
> 0 is explicitly documented to be the whole string

Doh! Should have had more coffee before looking that over.
