### ISSUE TITLE
Connection Drop and PgAudit disabled 

### ISSUE THREAD

**Issue by chris-cgsit** [pgaudit/pgaudit#226]
Hi,

We are trying to activate pgaudit on top of Postgres 15.4 for Produktion.

1. After Testing PG15.4 with pgaudit enabled in dev/test and Produktion test System, we get this error after a view minutes to hours only in our Produktion.  see log below
2. We had the same issue with postgres 12.2. now updated to 15.4 getting the same issues.

3. After this error all connections are dropped, and for new connections pgaudit will not log anything anymore. 

4. we did a lot of load and functional testings to the dbs with the logged named users... also jmeter based jdbc tests .. and are not able to reproduce this error.

Do you have any suggestions about the root cause here ? 

------------------------------------
**Log Output:**

202.. [22165]: [12-1] user=app-user,db=database-name DETAIL:  parameters: $1 = '2023-12-13 00:01:11.878', $2 = '2023-12-13 00:06:11.905', $3 = '2023-12-13 00:01:11.878', $4 = '2023-12-13 00:06:11.905'
**202.. [6259]: [1-1] user=[unknown],db=[unknown] PANIC:  cannot wait without a PGPROC structure
202.. [21800]: [11-1] user=,db= LOG:  server process (PID 6259) was terminated by signal 6: Aborted
202.. [21800]: [12-1] user=,db= LOG:  terminating any other active server processes**
202.. [6260]: [1-1] user=replicator,db=[unknown] FATAL:  the database system is in recovery mode
202.. [21800]: [13-1] user=,db= LOG:  all server processes terminated; reinitializing
202.. [21800]: [14-1] user=,db= LOG:  pgauditlogtofile extension initialized
202.. [6264]: [1-1] user=,db= LOG:  database system was interrupted; last known up at 2023-12-12 23:43:43 CET
202.. [6264]: [2-1] user=,db= LOG:  database system was not properly shut down; automatic recovery in progress
202.. [6264]: [3-1] user=,db= LOG:  redo starts at 120/9794EEA8
202.. [6264]: [4-1] user=,db= LOG:  invalid record length at 120/97A051D8: wanted 24, got 0
202.. [6264]: [5-1] user=,db= LOG:  redo done at 120/97A051B0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
202.. [6265]: [1-1] user=,db= LOG:  checkpoint starting: end-of-recovery immediate wait
202.. [6265]: [2-1] user=,db= LOG:  checkpoint complete: wrote 46 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.016 s, sync=0.010 s, total=0.049 s; sync files=33, longest=0.005 s, average=0.001 s; distance=728 kB, estimate=728 kB

System Setup:
- poststgreas main and standby server 
- 12 jboss instances with multiple connections to db connection pools
- paudti logging named user activity, but not application user

**Config:**

shared_preload_libraries = 'pgaudit,pgauditlogtofile'
pgaudit.log = 'WRITE,FUNCTION,ROLE,DDL,MISC_SET'
pgaudit.log_parameter = 'true'
pgaudit.log_directory = '/var/lib/pgsql/audit'
pgaudit.log_filename = 'audit-%Y-%m-%d.log'
pgaudit.log_connections = 'true'
pgaudit.log_disconnections = 'true'

**Versions**

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
# rpm -qa pgaudit17_15
pgaudit17_15-1.7.0-1.rhel7.x86_64

**Comment by chris-cgsit** [comment]
@dwsteele  could you have a look on this question please ?

**Comment by dwsteele** [comment]
Have you looked at https://github.com/fmbiete/pgauditlogtofile/issues/32 (found with a cursory search)?

**Comment by chris-cgsit** [comment]
> Have you looked at [fmbiete/pgauditlogtofile#32](https://github.com/fmbiete/pgauditlogtofile/issues/32) (found with a cursory search)?
yes .. but PGAuditLogToFile as RPM package is there only to version 1.5.10 for RHEL 7.7, and the fix seems in 1.5.11

@dwsteele could be the cause, but we are not able to reproduce this error in any test system. do you have a tip or script on howto repoduce the ERROR in  https://github.com/fmbiete/pgauditlogtofile/issues/32  ?

**Comment by dwsteele** [comment]
Sorry -- I've never seen the error before so no ideas on how to reproduce.

**Comment by chris-cgsit** [comment]
> Have you looked at [fmbiete/pgauditlogtofile#32](https://github.com/fmbiete/pgauditlogtofile/issues/32) (found with a cursory search)?

this issue solved our problem, and our systems are stable now. thanks
