### ISSUE TITLE
PgAudit stack is not empty

### ISSUE THREAD

**Issue by wzbnb001** [pgaudit/pgaudit#229]
PgAudit will output stack is not empty in the newest branch for pg12, 13, 14 and 15

How to reproduce:
```
postgres=# SHOW pgaudit.log;
 pgaudit.log 
-------------
 all
(1 row)
postgres=# CREATE TABLE part_test (c1 int, c2 int) PARTITION BY RANGE (c1);
CREATE TABLE
postgres=# CREATE TABLE part_test_1_to_10 PARTITION OF part_test FOR VALUES FROM (1) TO (10);
CREATE TABLE
postgres=# INSERT INTO part_test VALUES (generate_series(1,9));
INSERT 0 9
postgres=# CREATE OR REPLACE FUNCTION get_test_id(_ret REFCURSOR) RETURNS REFCURSOR
postgres-# LANGUAGE plpgsql IMMUTABLE AS $$
postgres$# BEGIN
postgres$#     OPEN _ret FOR select * from part_test;
postgres$#     RETURN _ret;
postgres$# END $$;
CREATE FUNCTION
postgres=# BEGIN;
BEGIN
postgres=# SELECT get_test_id('_ret');
 get_test_id 
-------------
 _reta
(1 row)
postgres=# FETCH ALL FROM _ret;
ERROR:  pgaudit stack is not empty 
```

In foreach in log_select_dml(), after checking the partition table, the partition is checked.
The partition seems to set to rte->requiredPerms = 0. Therefore, when processing of log_select_dml() is finished, "auditEventStack->auditEvent.commandTag = T_Invalid" is set.
https://github.com/postgres/postgres/blob/REL_12_17/src/backend/optimizer/util/inherit.c#L469
https://github.com/pgaudit/pgaudit/blob/REL_12_STABLE/pgaudit.c#L1049-L1078

Then when check the stack in `pgaudit_ProcessUtility_hook `, it will complain about there is command in the stack with tag invalid.

**Comment by dwsteele** [comment]
We have a preliminary fix for this in PR #230. Closing since there is now a PR.

However, this works in the current version if you remove `IMMUTABLE` from the function definition -- it is pretty clearly not immutable.
