### ISSUE TITLE
Need only Object Audit Logging in audit logs

### ISSUE THREAD

**Issue by divyn10** [pgaudit/pgaudit#236]
I am having postgres13.13 and I want to do auditing for some specific role. 
I have set `pgaudit.role=role` but I am getting both `SESSION` and `OBJECT` logs.

Is there any way I can disable SESSION logs they are creating a lot of noise and taking a lot of storage.

![image](https://github.com/pgaudit/pgaudit/assets/106735568/b15c0e54-7075-45f2-a7b5-23e67d15e1a3)

**Comment by dwsteele** [comment]
You have not provided your settings, so hard to be sure, but you probably just need to set `pgaudit.log = none`.

**Comment by divyn10** [comment]
![image](https://github.com/pgaudit/pgaudit/assets/106735568/473f5ac7-a35a-4469-9eeb-4efca170c760)
These are my pgaudit settings.


On setting `pgaudit.log = none` will it log `OBJECT` logs?

**Comment by dwsteele** [comment]
> On setting pgaudit.log = none will it log OBJECT logs?

Yes.
