### ISSUE TITLE
OBJECT message printed out regardless pgaudit.log_relation

### ISSUE THREAD

**Issue by ahouska** [pgaudit/pgaudit#25]
Despite pgaudit.log_relation being off, OBJECT log entry appears in addition
to SESSION.

LOG:  AUDIT: SESSION,2,1,READ,SELECT,,,SELECT * FROM a;,<not logged>
LOG:  AUDIT: OBJECT,2,1,READ,SELECT,TABLE,public.a,SELECT * FROM a;,<not logged>

If pgaudit.log_relation is on, the output looks correct

LOG:  AUDIT: OBJECT,2,1,READ,SELECT,TABLE,public.a,SELECT * FROM a;,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,TABLE,public.a,SELECT * FROM a;,<not logged>

but gdb shows that the SESSION entry is printed out in code path which should
actually print OBJECT message:

        /* Do relation level logging if auditLogRelation is set */
        if (auditLogRelation)
        {
            auditEventStack->auditEvent.logged = false;
            auditEventStack->auditEvent.granted = false;
            log_audit_event(auditEventStack);
        }

Besides that, the following part seems to me incorrect

    /*
     * If no tables were found that means that RangeTbls was empty or all
     * relations were in the system schema.  In that case still log a session
     * record.
     */
    if (!found)

because each iteration of the rangetable loop sets "found" unconditionally to
true and never sets it back to false.

Attached is my patch proposal. Do I seem to misunderstand the expected behavior?

[pgaudit_event_kind.diff.gz](https://github.com/pgaudit/pgaudit/files/787673/pgaudit_event_kind.diff.gz)

**Comment by dwsteele** [comment]
`log_relation` controls whether separate rows are output for each table in session logging.  This is more verbose but makes audit easier. 

I think you misunderstand the intent of the later code.  `found` will be false after the loop if there are no tables in `rangeTabls`, e.g. `select true`.
