### ISSUE TITLE
pgaudit still 

### ISSUE THREAD

**Issue by walpino** [pgaudit/pgaudit#26]
Hi there
we have a postgres 9.4 Installation with pgaudit for Audits user Actions

I guess it is the Version v1.0

is postgres 9.4 compatible with is the Version v1.2 
or do we have to upgrade postgres to 9.5 or higher?

there is a second question
we have a lot of Audits of pg_catalog

our Parameters are like 
                           pgaudit.log
-------------------------------------------------------------------
 read, write, privilege, user, definition, config, admin, function
(1 row)

pgaudit.log_catalog = off
so this should remove the most of the pg_catalog entires in the log file or not?

**Comment by dwsteele** [comment]
9.4 is not supported any of the versions in this repo.  The 9.4 version you are running is likely from 2nd Quadrant and will run on 9.5 and 9.6 as well.

`pgaudit.log_catalog = off` will disable logging of queries that are against the catalog only.
