### ISSUE TITLE
pgaudit for Windows

### ISSUE THREAD

**Issue by jssntcz** [pgaudit/pgaudit#27]
Hello, Please would it be possible to publish guidance on how to deploy pgaudit and analyzer for Windows? I thank you and have a nice day. George Barrel

**Comment by dwsteele** [comment]
Hi George,

This pgaudit project does not maintain a Windows build for the extension. There are Windows installers available from PostgreSQL support companies, including Crunchy (disclosure: where I work) and perhaps others.

Regards,
-David
