### ISSUE TITLE
pgaudit module with rpm

### ISSUE THREAD

**Issue by kaitoan2000** [pgaudit/pgaudit#30]
Hello,
I'm installing pgaudit with postgres 9.6 rpm, but I couldn't find how to install it without compile method.
Is there pgaudit with rpm install?
Regards,

**Comment by dwsteele** [comment]
The pgaudit project does not maintain any packages. There are RPM and Debian installers available from PostgreSQL support companies, including Crunchy (disclosure: where I work) and perhaps others.

Regards,
-David
