### ISSUE TITLE
How to install pgaudit when Postgres is already installed using apt repository?

### ISSUE THREAD

**Issue by thekgt** [pgaudit/pgaudit#31]
Hi,
I need to install pgaudit. According to Installation steps provided by pgaudit, I need to first install Postgres from source, then take checkout of pgaudit source code in it's contrib directory, and after that I'll install pgaudit. Currently Postgres has been installed on my machine from apt repo, there is contrib directory inside /usr/share/postgresql but required files like Makefile.global and contrib-global files. 
I have also downloaded postgres source and tried to clone pgaudit in it's contrib directory and then run 'make -s check'. But this also fails.
I can't install Postgres from source. How can I install pgaudit in this situation?

Thanks, 
Aman

**Comment by dwsteele** [comment]
The pgaudit project does not maintain any packages. There are RPM and Debian installers available from PostgreSQL support companies, including Crunchy (disclosure: where I work) and perhaps others.

Regards,
-David
