### ISSUE TITLE
ERROR:  could not find function "pgaudit_func_sql_drop" in file "/usr/lib/postgresql/9.6/lib/pgaudit.so"

### ISSUE THREAD

**Issue by agsyafaat** [pgaudit/pgaudit#32]
I'm getting error could not find function "pgaudit_func_sql_drop" in pgaudit.so file when try to drop a table. I had setup pgaudit (i use REL_9_6_STABLE) correctly without error in Postgresql 9.6.1 on Ubuntu...

**Comment by dwsteele** [comment]
You'll need to run `CREATE EXTENSION pgaudit` on any database where you would like to do audit logging.
