### ISSUE TITLE
log_statement_once=on does not work

### ISSUE THREAD

**Issue by JMLessard** [pgaudit/pgaudit#33]
I need to only log the first occurrence of query and DML.
I set log_statement_once=on in postgresql.conf and make sure that the parameter is not overwiden at the DB or role level.
Please find bellow a simple test case and result.
`select count(*) from poe;`
`show pgaudit.log_statement_once;`
` pgaudit.log_statement_once`
` ----------`
` on`
`select count(*) from poe;`
`select count(*) from poe;`

pg_log results
`LOG:  AUDIT: SESSION,2,1,READ,SELECT,,,select count(*) from poe;,<none>`
`LOG:  AUDIT: SESSION,3,1,MISC,SHOW,,,show pgaudit.log_statement_once;,<none>`
`LOG:  AUDIT: SESSION,4,1,READ,SELECT,,,select count(*) from poe;,<none>`
`LOG:  AUDIT: SESSION,5,1,READ,SELECT,,,select count(*) from poe;,<none>`

**Comment by dwsteele** [comment]
This setting only applies to each backend call.  So if there are multiple entry entries per backend call then the statement will one be logged once, in the first audit entry for that call.

Doing this across an entire backend session would require caching queries and would adversely affect performance.

**Comment by JMLessard** [comment]
Agree, thank you.
