### ISSUE TITLE
repeating log file entries

### ISSUE THREAD

**Issue by davidradernj** [pgaudit/pgaudit#35]
https://www.postgresql.org/docs/9.6/static/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-PRELOAD

"Note: On Windows hosts, preloading a library at server start will not reduce the time required to start each new server process; each server process will re-load all preload libraries. However, shared_preload_libraries is still useful on Windows hosts for libraries that need to perform operations at postmaster start time."

The code in _PG_init will be re-run for every backend process start on Windows. That means every 30 seconds when auto vacuum runs, the log message will be printed.

**Comment by jconway** [comment]
Not sure what happened to the thread, but yeah, I said exactly the same. Possibly we should demote the message from log to debug either in general or on Windows only.

**Comment by jconway** [comment]
Resolved with commit 9185dec
