### ISSUE TITLE
RHEL 6 Kernel Update breaks Fips compliance after PGAudit install

### ISSUE THREAD

**Issue by nickelsong** [pgaudit/pgaudit#36]
After installing pgaudit on a RHEL 6 system, postgres ver 9.5.6. Any kernel update would cause the system to hang on boot when FIPS is enabled (fips=1 in grub.conf)

Fix: Add line to /etc/dracut.conf
vi /etc/dracut.conf
### add this line 
install_items+=" /lib64/libz.so.1 "

Rebuild initramfs 
# dracut -v -f

Issue: 
Prior to pgaudit install, /boot/initramfs contains references to libz.so.1 
-rwxr-xr-x   1 root     root        88600 Oct  3  2012 lib64/libz.so.1.2.3
lrwxrwxrwx   1 root     root           13 May 11 03:13 lib64/libz.so.1 -> libz.so.1.2.3

After pgaudit is installed following reference is added
-rwxr-xr-x   1 root     root       112664 Feb  7 07:07 usr/pgsql-9.5/lib/libz.so.1 

Without adding the line above when initramfs is rebuilt as part of a kernel upgrade, the /lib64/libz.so.1 reference is dropped and boot will hang. The only way to get the system to boot is to edit the boot parameters and change fips=0, uninstall postgres, rebuild your initramfs, reboot, then re-install postgress/pgaudit.

The guide I followed was from here:
http://iase.disa.mil/stigs/app-security/database/Pages/edb-postgres.aspx
http://iasecontent.disa.mil/stigs/zip/U_PostgreSQL_9-x_V1R1_STIG.zip
U_PostgreSQL_9-x_V1R1_Supplemental.pdf

**Comment by jconway** [comment]
I have no idea where /usr/pgsql-9.5/lib/libz.so.1 comes from. Please run the following and report back:
  yum whatprovides /usr/pgsql-9.5/lib/libz.so.1
Also, you point to the EDB STIG as well as the community PostgreSQL STIG -- are you using EDB (proprietary) or community (open source) PostgreSQL? If the former, you should be asking for their support.

**Comment by nickelsong** [comment]
[root]# yum whatprovides /usr/pgsql-9.5/lib/libz.so.1
Loaded plugins: product-id, subscription-manager
No Matches found

[root]# yum whatprovides /lib64/libz.so.1
zlib-1.2.3-29.el6.x86_64 : The zlib compression and decompression library
Repo        : installed
Matched from:
Other       : Provides-match: /lib64/libz.so.1

We are using PostgreSQL but as you mentioned the STIG refers to EDB so I could have mixed the two up while following the guide, so I will need to review on my end. Overall it works as expected.

**Comment by jconway** [comment]
That matches what I expected to see. I'm not sure where you got  /usr/pgsql-9.5/lib/libz.so.1 but that is not a library I would expect to see in that location. Your system should be using the one provided by the zlib package in /lib64. If the rogue library is causing an issue I would archive it somewhere safe, ideally after figuring out how it got there in the first place.
