### ISSUE TITLE
Does this only work with postgres gloned from git repo?

### ISSUE THREAD

**Issue by payals** [pgaudit/pgaudit#37]
Makefile looks for the contrib directory, which doesn't exist on postgres when its installed from package or compiled from source downloaded from the website. "contrib" directory only exists in the postgres repo on git.

**Comment by jconway** [comment]
Build like this:
  USE_PGXS=1 make
  USE_PGXS=1 make install
Make sure you have the PostgreSQL development packages installed for your distribution.
