### ISSUE TITLE
How to include application users in audit

### ISSUE THREAD

**Issue by rbeers** [pgaudit/pgaudit#38]
Can this extension include session variables in the audit file?  For example, if we are not using a 1:1 mapping between application users and database users, we would do something like this:

SET my.username = 'tomas'

I couldn't find anything in the log prefix variables where we could inject something like:
current_setting('my.username')

I essentially want to do what is outlined in this blog post but ensure auditing includes the application user.  https://blog.2ndquadrant.com/application-users-vs-row-level-security/

Thanks,
Rob

**Comment by dwsteele** [comment]
`pgaudit` can log the `SET my.username = 'tomas'` statement but it can't include the value of the GUC with every audit statement.

If you were parsing the log yourself you could associate the SET with other commands that happen later in the same session.

**Comment by fbrcode** [comment]
@rbeers, do you have an example of your implementation outcome? I'm facing a similar situation where I'm expecting to have more information on who is doing what from the database perspective.

**Comment by dyuan-boxlabs** [comment]
@rbeers @fbrcode facing the exact same issue, we're using Prisma as our ORM and all db access is done through the same db user ("api_user") so as far as I can tell there is no way for pgaudit to perform app-user level auditing

**Comment by dwsteele** [comment]
Yes, you could add `application_name` (`%a`) to `log_line_prefix`: https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-LINE-PREFIX.

**Comment by tbenbrahim** [comment]
`application_name` is useful if one opens a connection for every request. This is not the case for a web application with a connection pool.
