### ISSUE TITLE
Easier, clearer release policy?

### ISSUE THREAD

**Issue by praiskup** [pgaudit/pgaudit#39]
Hi, looking at `git diff REL_10_STABLE REL9_5_STABLE`, it seems to be that the differences are so small that it would be pretty easy to go with `#if/#ifdef` conditions and have only one version of the software, allowing to build that against all the PostgreSQL versions (and removing the need to do manual plugin upgrade after `pg_upgrade`).  Also, users feel more comfortable to use the latest versions of PostgreSQL plugins (even against older postgres releases).

**Comment by dwsteele** [comment]
Hi Pavel,

This has already been discussed at length -- see #22.
