### ISSUE TITLE
Compile on RHEL 7

### ISSUE THREAD

**Issue by bjorntj** [pgaudit/pgaudit#41]
Tried to compile this extension on RedHat Enterprise 7 and I get the following error:

> make -s check
pgaudit.c: In function ‘stack_push’:
pgaudit.c:358:66: error: macro "AllocSetContextCreate" passed 5 arguments, but takes just 3
                                          ALLOCSET_DEFAULT_MAXSIZE);
                                                                  ^
pgaudit.c:354:20: error: ‘AllocSetContextCreate’ undeclared (first use in this function)
     contextAudit = AllocSetContextCreate(CurrentMemoryContext,
                    ^
pgaudit.c:354:20: note: each undeclared identifier is reported only once for each function it appears in
pgaudit.c: In function ‘pgaudit_ddl_command_end’:
pgaudit.c:1485:53: error: macro "AllocSetContextCreate" passed 5 arguments, but takes just 3
                             ALLOCSET_DEFAULT_MAXSIZE);
                                                     ^
pgaudit.c:1480:20: error: ‘AllocSetContextCreate’ undeclared (first use in this function)
     contextQuery = AllocSetContextCreate(
                    ^
pgaudit.c: In function ‘pgaudit_sql_drop’:
pgaudit.c:1596:53: error: macro "AllocSetContextCreate" passed 5 arguments, but takes just 3
                             ALLOCSET_DEFAULT_MAXSIZE);
                                                     ^
pgaudit.c:1591:20: error: ‘AllocSetContextCreate’ undeclared (first use in this function)
     contextQuery = AllocSetContextCreate(
                    ^
make[1]: *** [pgaudit.o] Error 1
make: *** [temp-install] Error 2

**Comment by dwsteele** [comment]
Are you trying to build this on PG < 9.5?  Only 9.5 and higher are supported.

**Comment by bjorntj** [comment]
No, I am trying to build for PG 10.1

**Comment by dwsteele** [comment]
Just tried our test build and it works.  You can see that procedure here: https://github.com/pgaudit/pgaudit/blob/master/test/Vagrantfile

This builds pgaudit using the pre-built binaries from yum.postgres.org.   It looks to me like you are building from master where this prototype has changed.

**Comment by bjorntj** [comment]
Hmmm... You are absolutely correct.. I just checked out postgresql from the repos but downloaded the source code for 10.1 now and now I have a working pgaudit extension... :)

**Comment by dwsteele** [comment]
No problem!
