### ISSUE TITLE
ERROR: could not load library ../pg95/lib/postgresql/pgaudit.dll": The specified module could not be found.

### ISSUE THREAD

**Issue by Brysounds** [pgaudit/pgaudit#42]
I am using Postgres 9.5 on Win10. I have pg installed successfully. However, I am unable to get the pgaudit 1.0.6  extension to create. I have followed the steps in the readme file with no luck. The error that I am seeing now is the following when running the CREATE EXTENSION command in psql:

**ERROR: could not load library "C:/POSTGR~1/pg95/../pg95/lib/postgresql/pgaudit.dll": The specified module could not be found.**

The dll is located in the path and the permissions are set just as the rest.

Please help... Thank you in advance for your time and knowledge.

**Comment by Brysounds** [comment]
I have fixed the issue that I was running into. I could not get pgaudit to install using cygwin so I used pgc instead and it worked perfectly.

**Comment by dwsteele** [comment]
Hi -- sorry I didn't have a chance to look at this, but glad you figured it out.  I though Cygwin would work, but Windows is not my forte.

**Comment by Brysounds** [comment]
No worries thank you responding.
