### ISSUE TITLE
Adding pgAudit to the official PostgreSQL docker image

### ISSUE THREAD

**Issue by eladtamary** [pgaudit/pgaudit#44]
Hi, 
Is there an option to "plug" pgAudit to the official PostgreSQL docker image?
Thanks,
Elad

**Comment by dwsteele** [comment]
We don't have any involvement with that project, but you are certainly welcome to suggest it to the maintainers.

**Comment by eladtamary** [comment]
I will try to rephrase my question.
Is it necessary to compile PostgreSQL and pgAudit one after the other as mentioned in the README.md?
Can I compile/install pgAudit on a machine that PostgreSQL is already installed in?

Thanks,
Elad

**Comment by dwsteele** [comment]
You can build using PGXS instead:
```
make -C [pgaudit-dir] install USE_PGXS=1
```
You'll probably need to install some development tools:
```
yum install -y postgresql96-devel gcc openssl-devel
```
Just replace with you version of Postgres.

**Comment by eladtamary** [comment]
Thanks for the help!
It worked.

**Comment by gengen1988** [comment]
Hi, 

Thanks for sharing. I think this is no need to install the build tools when using official image. Just install it from package manager, like this:

```Dockerfile
# Dockerfile

FROM postgres:11
RUN apt-get update && apt-get install -y --no-install-recommends \
  postgresql-$PG_MAJOR-pgaudit
```

And run with command to load the extension:
```yaml
# docker-compose.yaml

version: "3"
services:
  postgres:
    image: <yourimage>
    command: postgres -c shared_preload_libraries=pgaudit
```

Write configs in SQL for more flexibility:
```sql
# sql

CREATE EXTENSION pgaudit;
ALTER SYSTEM SET pgaudit.log_catalog = off;
ALTER SYSTEM SET pgaudit.log = 'all, -misc'
ALTER SYSTEM SET pgaudit.log_relation = 'on'
ALTER SYSTEM SET pgaudit.log_parameter = 'on'
```

See "Additional Extensions" chapter: https://hub.docker.com/_/postgres

**Comment by zll600** [comment]
Hi,

I'm curious if there is any plan to provide Docker images like `pgaudit/pgaudit`? 

I'd like to help if this is in the roadmap.
