### ISSUE TITLE
PGAUDIT install

### ISSUE THREAD

**Issue by AderPG** [pgaudit/pgaudit#46]
Hi.
I have a problem with the installation of pgaudit, I have already tried it in several environments and the result is the same 

**I am following the next steps:**
1. Compile and Install
Clone the PostgreSQL repository:
git clone https://github.com/postgres/postgres.git

2.-Checkout REL9_6_STABLE branch:
git checkout REL9_6_STABLE

3.- Make PostgreSQL:
./configure
make install -s

4.-Change to the contrib directory:
cd contrib

5.- Clone the pgAudit extension:
git clone https://github.com/pgaudit/pgaudit.git

6.-Change to pgAudit directory:
cd pgaudit

7.- Build pgAudit and run regression tests:
make -s check

8.- Install pgAudit:
make install

**However at point 7 it fails.**
[root@pgsql-desa01 pgaudit]# make -s check
pgaudit.c:38:27: fatal error: utils/varlena.h: No such file or directory
 #include "utils/varlena.h"
                           ^
compilation terminated.
make[1]: *** [pgaudit.o] Error 1
make: *** [temp-install] Error 2

**indeed the file varlena.h  does not exist and i dont know why.**

**Trying solutions I have created the file according to source code, however it fails again with another error.**

[root@pgsql-desa01 pgaudit]# make -s check
In file included from pgaudit.c:38:0:
../../src/include/utils/varlena.h:19:12: error: conflicting types for ‘varstr_cmp’
 extern int varstr_cmp(const char *arg1, int len1, const char *arg2, int len2, Oid collid);
            ^
In file included from pgaudit.c:31:0:
../../src/include/utils/builtins.h:848:12: note: previous declaration of ‘varstr_cmp’ was here
 extern int varstr_cmp(char *arg1, int len1, char *arg2, int len2, Oid collid);
            ^
pgaudit.c:1351:29: error: unknown type name ‘QueryEnvironment’
                             QueryEnvironment *queryEnv,
                             ^
pgaudit.c: In function ‘_PG_init’:
pgaudit.c:1972:27: error: ‘pgaudit_ProcessUtility_hook’ undeclared (first use in this function)
     ProcessUtility_hook = pgaudit_ProcessUtility_hook;
                           ^
pgaudit.c:1972:27: note: each undeclared identifier is reported only once for each function it appears in
pgaudit.c: At top level:
pgaudit.c:410:1: warning: ‘stack_valid’ defined but not used [-Wunused-function]
 stack_valid(int64 stackId)
 ^
make[1]: *** [pgaudit.o] Error 1
make: *** [temp-install] Error 2
[root@pgsql-desa01 pgaudit]# ^C

****Can someone help me? Thnsks****

**Comment by AderPG** [comment]
Add ..
Postgresql  9.6 on CentOS Linux 7.4 

...I appreciate any  #help

**Comment by dwsteele** [comment]
The pgaudit master branch is for development and currently builds only on PG10.

You'll want to check out `REL9_6_STABLE` for the 9.6 version of pgaudit, or better yet use the latest release tag for 9.6, `1.1.1`.
