### ISSUE TITLE
pgaudit install question

### ISSUE THREAD

**Issue by sharadov** [pgaudit/pgaudit#48]
I have postgres 9.5.5 installed and want to install the pgaudit extension.
Do you still need to clone the PostgreSQL git repo and build it, before cloning the pgaudit repo?
Is downloading and building postres a pre-req to the pgaudit install?

**Comment by sharadov** [comment]
I realized that the extension needs access to the header files. That said in my case I had installed the pgaudit extension on a test machine and was able to just copy the pgaudit related libraries and sql files to the postgres install directory and get it working. But this will only work if the source and destination are on the same postgres major/minor version.

**Comment by dwsteele** [comment]
You might consider getting the pre-built packages from the apt/yum repos at postgresql.org.

**Comment by sharadov** [comment]
will do, thanks!
