### ISSUE TITLE
No logging if action on child (inherited) table's row is done on the parent (inheriting) table.

### ISSUE THREAD

**Issue by achix** [pgaudit/pgaudit#49]
In the case of inheritance if we GRANT access to the auditor role on some child table, and not the parent, actions on the parent table which translate to actions on rows of the child table will not be logged.

**Comment by dwsteele** [comment]
Perhaps I'm missing something, but this sounds sensible to me.

**Comment by dwsteele** [comment]
Are you using rules or triggers to decide which child table the data will go into?  It seems like triggers would work way you are hoping, while rules would not.  I haven't tested it, though.

**Comment by achix** [comment]
Hello, children tables and father table share the same sequence as default ID so it is (semi)guaranteed that the id will be unique across the whole hierarchy. So we insert only to children tables, and the decision id made on search_path: father, children have same name but different schemas. But we select/update all of them, including the father. Updates/selects on the father table are realized by selects/updates on the children rows.

Example : 

 select * from someschema1.ourtable where id = <someid>;
correctly logs
however the same select, (effectively), 
select * from public.ourtable where id = <someid>;
does not log, despite selecting the exact same row.

**Comment by dwsteele** [comment]
I don't think pgAudit should be trying to automagically figure out what you are intending to audit.  First, this could have strange side effects.  Second, trying to determine the hierarchy for each table in a query would severely impact performance.

It appears the answer is to grant the auditor role on any table that you want to audit inserts on.

**Comment by achix** [comment]
Hi, thanks, that makes sense!
