### ISSUE TITLE
Cant see OBJECT_TYPE and OBJECT_NAME in DDL operation

### ISSUE THREAD

**Issue by tigranav** [pgaudit/pgaudit#51]
Cant see OBJECT_TYPE and OBJECT_NAME in DDL operation.

**my settings:** 

postgres: 9.6
pgaudit: pgaudit11_96-1.1.1-1.rhel7.x86_64.rpm
```
shared_preload_libraries=pg_stat_statements, pg_hint_plan, pg_cron, pgaudit
pgaudit.log=ddl,role
log_connections=on
log_disconnections=on
log_line_prefix=%t [%p-%l] %q%u@%d %i
```
**action:**
```
music=# create table mt2 (b int);
CREATE TABLE
```
**result:** 

`2018-05-28 10:33:08 UTC [2645-4] postgres@music CREATE TABLE LOG: AUDIT: SESSION,2,1,DDL,CREATE TABLE,,,create table mt2 (b int);,<none>
`

**Comment by dwsteele** [comment]
Did you run `CREATE EXTENSION pgaudit`?  It looks like you are missing the event triggers.

**Comment by dwsteele** [comment]
Hopefully the suggestion above fixed the issue.
