### ISSUE TITLE
Pgaudit install on Centos   7.3

### ISSUE THREAD

**Issue by lres7399** [pgaudit/pgaudit#52]
Hi,

I encounter problems when configuring pgaudit with  Postgresql 9.6.3 on Centos 7.3

I follow these steps:

1.Compile and Install
Clone the PostgreSQL repository:
git clone https://github.com/postgres/postgres.git
2.-Checkout REL9_6_STABLE branch:
git checkout REL9_6_STABLE

3.- Make PostgreSQL:
./configure
make install -s

4.-Change to the contrib directory:
cd contrib

5.- Clone the pgAudit extension:
git clone https://github.com/pgaudit/pgaudit.git

6.-Change to pgAudit directory:
cd pgaudit

7.- Build pgAudit and run regression tests:
make -s check

8.- Install pgAudit:
make install

However at point 7 it fails.
[XXx]# make -s check
pgaudit.c:38:27: fatal error: utils/varlena.h: No such file or directory
#include "utils/varlena.h"
^
compilation terminated.
make[1]: *** [pgaudit.o] Error 1
make: *** [temp-install] Error 2

Look's like there are no varlena header.

Some one can tell me what's wrong here ,please ?

**Comment by dwsteele** [comment]
You're trying to build against PG9.6 but master in pgaudit if for PG10.  Trying checking out the pgaudit REL9_6_STABLE branch.

**Comment by dwsteele** [comment]
Hopefully the suggestion above fixed your issue.

We also added a clarification about this to the documentation.
