### ISSUE TITLE
Filter audit on users

### ISSUE THREAD

**Issue by stopitallready** [pgaudit/pgaudit#53]
It would be great if we could set up a filter to audit only specific users. Currently it's either session - which is everything, or objects - which is everyone. We have noisy users (service accounts) and it would be great to be able to exclude them.

**Comment by dwsteele** [comment]
The GUCs can be set per user, so this should do the trick.
```
alter user <service_account> set pgaudit.role = '';
```

**Comment by stopitallready** [comment]
Awesome! Thanks.
