### ISSUE TITLE
Cannot exclude role from auditing

### ISSUE THREAD

**Issue by lordhadespl** [pgaudit/pgaudit#54]
Hello,
When I set session audit all, and altered role1 with pgaudit.log=none. The role1 is still audited.
Is it expected? Any possibility to exclude the role from being audited?

I had set session audit by:

```
# postgresql.conf
pgaudit.role = 'auditor'
pgaudit.log = 'READ,WRITE,FUNCTION,ROLE,DDL,MISC' # READ,WRITE,FUNCTION,ROLE,DDL,MISC
pgaudit.log_parameter = on
pgaudit.log_statement_once = on
pgaudit.log_catalog = off
```
And I had altered role1 with no audit:
```
psql
ALTER ROLE role1 SET pgaudit.log='none';
```

**Comment by patricia-finra** [comment]
I have also observed that if the audit settings are done at db level(alter database xxx set pgaudit.log=xxx;), then set for an individual role, sometimes it doesn't take effect at all. Other times if a reversal is done at the individual setting, pgaudit ignores the new settings altogether. 

Having reviewed the test case, seems there is no testing done at db/system level, everything is a combination of session level (SET pgaudit.log = xxx; in the session) and role level (alter role xxx set pgaudit.log=xxx;).
