### ISSUE TITLE
Installing pgaudit 1.2 binary (for Postgrss 10.4) on SUSE SLES 12

### ISSUE THREAD

**Issue by tviscard** [pgaudit/pgaudit#55]
Hi,

Is there an rpm package avail to allow us to  install pgaudit 1.2 binary (for Postgres 10.4) on SUSE SLES 12.3
Or what would be the best way to install pgaudit.
Only binary postgres 10.4 was installed on our server running SUSE SLES 12.3

Thx
Tony

**Comment by dwsteele** [comment]
I'm not aware of any packages for SUSE and a quick search does not turn up anything.

pgaudit can be built from a binary distribution using PGXS (see https://github.com/pgaudit/pgaudit/blob/master/test/Vagrantfile#L25 for an example) but you'll need various build tools to do it.
