### ISSUE TITLE
pgaudit on solaris does not write so syslog but to well to csvlog

### ISSUE THREAD

**Issue by omontue** [pgaudit/pgaudit#56]
I installed Postgres 10 on Solaris together with pgaudit. After compiling everything I created a database and set it up to log to syslog and csvlog. I want to audit any changes to roles. The postgres csv-log contains changes to role but not the syslog. When I produce an error (eg. select * from not-existing_table) the error is also visible in the syslog. Can you assist me to sent also the role-changes to syslog, please?

Kind regards,
Oliver

Attached are the parameter settings:

# REPORTING AND LOGGING
#------------------------------------------------------------------------------

# - Where to Log -

log_destination = 'syslog,csvlog'               # Valid values are combinations of
                                        # stderr, csvlog, syslog, and eventlog,
                                        # depending on platform.  csvlog
                                        # requires logging_collector to be on.

# This is used when logging to stderr:
logging_collector = on          # Enable capturing of stderr and csvlog
                                        # into log files. Required to be on for
                                        # csvlogs.
                                        # (change requires restart)

# These are only used if logging_collector is on:
log_directory = '/usr/local/postgres/data/pg_log'                       # directory where log files are written,
                                        # can be absolute or relative to PGDATA
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log' # log file name pattern,
                                        # can include strftime() escapes
log_file_mode = 0600                    # creation mode for log files,
                                        # begin with 0 to use octal notation
#log_truncate_on_rotation = off         # If on, an existing log file with the
                                        # same name as the new log file will be
                                        # truncated rather than appended to.
                                        # But such truncation only occurs on
                                        # time-driven rotation, not on restarts
                                        # or size-driven rotation.  Default is
                                        # off, meaning append to existing files
                                        # in all cases.
log_rotation_age = 1d                   # Automatic rotation of logfiles will
                                        # happen after that time.  0 disables.
log_rotation_size = 1GB         # Automatic rotation of logfiles will
                                        # happen after that much log output.
                                        # 0 disables.

# These are relevant when logging to syslog:
syslog_facility = 'local0'

# Add settings for extensions here
shared_preload_libraries = 'pgaudit'
pgaudit.log_catalog='on'
pgaudit.log_level='NOTICE'
pgaudit.log_parameter='on'
pgaudit.log_relation='off'
pgaudit.log_statement_once='off'
pgaudit.log='role'

**Comment by omontue** [comment]
I think, I found the reason. I can set pgaudit.log_level to notice but still in CSV-Log the log_level ist LOG which is not applicable for syslog. Can you please check if this is a bug? I am using version 10.5 for solaris compiled in 64Bit.

Thanks a lot.
Oliver

**Comment by dwsteele** [comment]
pgAudit will only use `LOG` level unless `pg_audit.log_client=on`.  This is to prevent audit messages from being visible to the end user.

The documentation for this option was accidentally lost in 83a2f4e6 but has been restored now: https://github.com/pgaudit/pgaudit/blob/REL_10_STABLE/README.md#pgauditlog_client
