### ISSUE TITLE
make install USE_PGXS=1 ends up with Error 1

### ISSUE THREAD

**Issue by AGulshan** [pgaudit/pgaudit#57]
Hi!
I'm trying to install pgaudit
When I try to run '**make install USE_PGXS=1** ' it ends up with following error
-------------------
# make install USE_PGXS=1
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgaudit.o pgaudit.c
pgaudit.c:13:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [pgaudit.o] Error 1
----------------------
**My env:**
psql (10.5)
Linux 3.10.0-514.26.2.el7.x86_64

**Comment by dwsteele** [comment]
It looks like you haven't installed the development headers.  See https://github.com/pgaudit/pgaudit/blob/master/test/Vagrantfile for a complete example.

**Comment by rajatdey80** [comment]
I do have same problem. , Unfortunately. it did not work even after installing. all. the packages. . I can see. the. file. heads file in server. . But still it says missing file and directory.

**Comment by rajatdey80** [comment]
Problem solved after installing various packages . Please check if you any older version installed in the same server if clean it .
