### ISSUE TITLE
setting pgaudit.role for a role/user with a non superuser role

### ISSUE THREAD

**Issue by stopitallready** [pgaudit/pgaudit#59]
What permissions, if possible, does a non superuser have to have in order to set the pgaudit.role and pgaudit.log on a another user/role? After creating the new user/role and attempting to set the pgaudit parameters I get the following error - "ERROR:  permission denied to set parameter "pgaudit.role".

**Comment by stopitallready** [comment]
Just to clarify, this error happened to the role that created the second role. After creating the role I would like to audit it.

**Comment by dwsteele** [comment]
Only the superuser can set modify audit settings.  If you would like to delegate this to other users then look at the set_role exentension.

**Comment by stopitallready** [comment]
Thanks!
