### ISSUE TITLE
Improvement: prompt when multiple PostgreSQLs are installed

### ISSUE THREAD

**Issue by HankAviator** [pgaudit/pgaudit#69]
I installed PostgreSQL 11 on Ubuntu, not knowing it doesn't **update** (or overwrite) the old version (10) but keeping it. When I successfully built and installed pgAudit and tried to start PostgreSQL with it, PostgreSQL outputs a  fatal error to syslog: `could not access file "pgaudit": No such file or directory`.
This was because pgAudit installed the libs to PostgreSQL 10, instead of 11's directory. Maybe a few lines will be fool-proof and save a lot of confusions.

**Comment by dwsteele** [comment]
It's not clear to me how pgAudit would be able to do that since we're mostly using PG infrastructure for the build.  If you have a patch in mind I'd be glad to look at it.
