### ISSUE TITLE
Audit log problem with CREATE TABLE AS

### ISSUE THREAD

**Issue by harada-toshi** [pgaudit/pgaudit#7]
# audit log problem, "CREATE TABLE AS"

Hi.

I am testing the pgaudit(https://commitfest.postgresql.org/9/463/).
(use "http://www.postgresql.org/message-id/56B0101B.6070704@pgmasters.net" attached patch on 9.6-devel)

The following issues exists in the audit log output of the "CREATE TABLE AS" statement.

- Row of  "class READ" is two. Is not that redundant?
- "Class READ" in the second row ,invalid value (?d?) for object_name has been set. 

# Reproduce:
## pgaudit configuration (with postgresql.conf)
```
shared_preload_libraries = 'pgaudit'
pgaudit.log = 'all'
```
## sql script (test.sql)
```
CREATE TABLE tmp (id int, data text);
CREATE TABLE tmp2 AS (SELECT * FROM tmp); -- two problem.
```
## run
```
psql -U postgres test -f test.sql
```
## audit log

```
LOG:  AUDIT: SESSION,1,1,DDL,CREATE TABLE,,,"CREATE TABLE tmp (id int, data text);",<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,,,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
LOG:  AUDIT: SESSION,2,1,READ,SELECT,TABLE,?d?,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
LOG:  AUDIT: SESSION,2,2,DDL,CREATE TABLE AS,,,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
```

**Comment by dwsteele** [comment]
Hmmm, that's interesting.  I'll have to take a look and see if I can reproduce under 9.5.

Note that I'm am no longer supporting the CF patch that I submitted for 9.6.  Only the pgaudit module here on github will be supported for 9.5.  I'll be working on 9.6 support later in the summer.

**Comment by harada-toshi** [comment]
It was reproduced in version 9.5 + pgaudit-1.0.0.

```
LOG: AUDIT: SESSION, 1,1, DDL, CREATE TABLE ,,, "CREATE TABLE tmp (id int, data text);", <not logged>
LOG: AUDIT: SESSION, 2,1, READ, SELECT ,,, CREATE TABLE tmp2 AS (SELECT * FROM tmp);, <not logged>
LOG: AUDIT: SESSION, 2,1, READ, SELECT, TABLE, ??? R, CREATE TABLE tmp2 AS (SELECT * FROM tmp);, <not logged>
LOG: AUDIT: SESSION, 2,2, DDL, CREATE TABLE AS ,,, CREATE TABLE tmp2 AS (SELECT * FROM tmp);, <not logged>
```

**Comment by harada-toshi** [comment]
Even in "CREATE MATERIALIZED VIEW" command, the same problem occurs.
(PostgreSQL 9.5.1 + pgaudit-1.0.0)

```
LOG:  AUDIT: SESSION,21,1,READ,SELECT,,,"CREATE MATERIALIZED VIEW mv_accounts AS SELECT aid, bid, abalance FROM pgbench_accounts ;",<not logged>
LOG:  AUDIT: SESSION,21,1,READ,SELECT,TABLE,??R,"CREATE MATERIALIZED VIEW mv_accounts AS SELECT aid, bid, abalance FROM pgbench_accounts ;",<not logged>
LOG:  AUDIT: SESSION,21,2,DDL,CREATE MATERIALIZED VIEW,,,"CREATE MATERIALIZED VIEW mv_accounts AS SELECT aid, bid, abalance FROM pgbench_accounts ;",<not logged>
```
