### ISSUE TITLE
Is there any plans pg take in pgaudit?

### ISSUE THREAD

**Issue by hasefumi23** [pgaudit/pgaudit#70]
Hi I'm a beginner of PostgreSQL. I have a question.
Is there any plans pg take in `pgaudit` as built-in(core) functionality?

I'm using pg on my work, we need to audit functionality, and We would like to use `pgaudit` since it has some rich feature.
I know pg took in pgaudit as core at once but immediately reverted a while ago.
And I saw some post that pg is discussing whether taking in pgaudit or not. But I can't sure that it's already decided or not.
So I ask at here.
Is there any plans pg take in pgaudit?
If it's already planed, it would be nice!

Thanks.

**Comment by dwsteele** [comment]
pgAudit was rejected both times we tried to submit it to core.  We have no plans to submit it again.

**Comment by hasefumi23** [comment]
Got it.
Thank you!
