### ISSUE TITLE
PgAudit in Windows

### ISSUE THREAD

**Issue by gustavoDeMaria** [pgaudit/pgaudit#71]
Is there a tutorial on how to do the installation on windows?

**Comment by njesp** [comment]
I struggled a somewhat with this a while back. I described my findings here: https://github.com/njesp/build_pgaudit_on_windows

**Comment by dwsteele** [comment]
Thanks, Niels!

**Comment by njesp** [comment]
You're welcome. David, if you think it could be of value, you are free to include my writeups or to refer to it from the readme/other documentation.

**Comment by njesp** [comment]
I have adapted my description of how to compile 1.4 for Windows to Postgres 12.1 using Visual Studio 2019 Community Edition. The description is here: https://github.com/njesp/build_pgaudit_on_windows/blob/master/README_12.1.md
