### ISSUE TITLE
Exclude role/user in object auditing

### ISSUE THREAD

**Issue by khetank** [pgaudit/pgaudit#73]
Hello,

I got object auditing enabled for my PG database. My objective it to have AUDIT only for non-system users. Is there a way I can have AUDIT enabled for a table for all users/roles except couple of system users. (I would not want AUDITING on say table T1 for user U1 and U2 but all other users).

Thanks

**Comment by dwsteele** [comment]
`ALTER ROLE ... SET` is the best way to do this.  See https://github.com/pgaudit/pgaudit#settings.

**Comment by ventsislav-georgiev** [comment]
@dwsteele Using GCP's CloudSQL the superuser role is [not available](https://cloud.google.com/sql/docs/postgres/users#superuser_restrictions) and role/user configuration settings cannot be modified. Is there an alternative way to exclude role/user from the logs?

**Comment by cthart** [comment]
Sorry to resurrect this old issue, but I'm facing the same requirements but can't figure out how to solve it.

My client has several tables containing sensitive data. These are loaded by batch job. All operations (queries and DML) on the table by the batch job's user shouldn't be audited as that would flood the logs. But all other access to the table (queries and DML) by all other users should be audited.

Is it possible to achieve this with pgAudit, and if so, how?
