### ISSUE TITLE
UPDATE statement on multiple lines

### ISSUE THREAD

**Issue by deworn** [pgaudit/pgaudit#75]
Hi,

we're having problem with multiple lines for UPDATE statement. Every other statement is ok - meaning it's on one line. But UPDATE is often separated to several lines each logged as it's own message.

Ofc we could probably join them somehow or get around this but we'd like to know if there is something we can do on pgAudit side first.

Basically, UPDATE looks similar to this:
AUDIT: OBJECT,3,1,READ,SELECT,TABLE,public.account_role_map,select account.password,
       account_role_map.role_id
  from account
       inner join account_role_map
            on account.id = account_role_map.account_id,<not logged>

And we'd like them to look like this:
AUDIT: OBJECT,3,1,READ,SELECT,TABLE,public.account_role_map,select account.password,account_role_map.role_id  from account inner join account_role_map on account.id = account_role_map.account_id,<not logged>

Is it possible?

Thanks, Petr

**Comment by dwsteele** [comment]
The linefeeds are mostly likely in the original statement that was passed to PostgreSQL.  You can use CSV log format if you need to parse queries reliably.  See https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG.
