### ISSUE TITLE
ERROR:  cache lookup failed for type 2

### ISSUE THREAD

**Issue by rklaus77** [pgaudit/pgaudit#77]
We've had pgaudit on postgresql 11.5 for several weeks.

Today I turned on pgaudit.log_parameter for the first time and we started getting the above error on a procedure call.

With it ON we get 

bill10=> CALL sp3_en_update_price(169245);
NOTICE:  update 2
NOTICE:  MESSAGE_TEXT        = cache lookup failed for type 2
NOTICE:  PG_EXCEPTION_DETAIL =
NOTICE:  PG_EXCEPTION_HINT   =
ERROR:  cache lookup failed for type 2

pgaudit            | 1.3.1   | acct       | provides auditing functionality
 
PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit

**Comment by pikkmees** [comment]
We have same issue with Centos 7.6.1810 
 postgresql11-server-11.4-1PGDG.rhel7.x86_64
 pgaudit13_11-1.3.0-1.rhel7.x86_64
In case when pgaudit is off, application can work well, after turning it on it give error in different application and different type:
ERROR:  cache lookup failed for type 2
ERROR:  cache lookup failed for type 123956
ERROR:  cache lookup failed for type 133833
ERROR:  cache lookup failed for type 143307
ERROR:  cache lookup failed for type 2

**Comment by svb007** [comment]
We have the same issue on CentOS Linux release 7.6.1810
postgresql11-server-11.5-1PGDG.rhel7.x86_64
pgaudit13_11-1.3.0-1.rhel7.x86_64
I have set the following settings for a specific role
ALTER ROLE "%s" SET pgaudit.log = 'all'
ALTER ROLE "%s" SET pgaudit.log_relation = 'on'

Logging worked fine for the user for about 6 weeks, and then all of a sudden started frequently generating these errors :
ERROR:  cache lookup failed for type 1213477463
ERROR:  cache lookup failed for type 2
etc.

After I reset the pgaudit.log parameter on that role, the errors stopped.

**Comment by svb007** [comment]
I my case I managed to figure out that my errors got triggered when I enabled system-wide parameter logging in order to log access to a specific table :
ALTER SYSTEM SET pgaudit.log_relation = 'on'
ALTER SYSTEM SET pgaudit.log_parameter = 'on'
ALTER SYSTEM SET pgaudit.role = '%s' 
GRANT ALL ON TABLE %s TO "%s

I am confident that https://github.com/pgaudit/pgaudit/issues/65 will fix my issues

**Comment by WatchJiang** [comment]
> I am confident that the fix mentioned in #65 will fix my issues

Yes I think so. We have the same issue. We install pgaudit RPM package from postgres community YUM repository, it's 1.3.0-1. Then I compile and install pgaudit from source code with stable branch, the issue is fixed. Looks like the RPM package needs to upgrade.

**Comment by dwsteele** [comment]
This bug was fixed at https://github.com/pgaudit/pgaudit/commit/b2040b6e6c74718afd41b4ba46243fc31a286cfa (and backpatched to older branches).

It looks like the yum package needs an update.  @devrimgunduz?

**Comment by devrimgunduz** [comment]
Updated the package 2 days ago. :)
