### ISSUE TITLE
No audit log when turning off pgaudit

### ISSUE THREAD

**Issue by WatchJiang** [pgaudit/pgaudit#78]
Hi,

pgaudit.log='all', or set with MISC option at instance level.
Superuser login and run command: set pgaudit.log='none';
In this case there is no audit log print to log file, we have no idea when the superuser turn off pgaudit.

Is it possible to at least print one message to log file before it takes effect?

As I can notice log_statement can print such log before turning off logging if someone run: set log_statement='none';
However log_statement would print plain text password to log file which is not OK in our environment.

**Comment by WatchJiang** [comment]
Some steps to reproduce the issue, I can think of 3 scenarios

postgres=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 11.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

postgres=# \dx
                   List of installed extensions
  Name   | Version |   Schema   |           Description
---------+---------+------------+---------------------------------
 pgaudit | 1.3.1   | public     | provides auditing functionality
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# show pgaudit.log;
 pgaudit.log
-------------
 all
(1 row)

postgres=# set pgaudit.log_level='NOTICE';
SET
postgres=# set pgaudit.log_client='on';
NOTICE:  AUDIT: SESSION,4,1,MISC,SET,,,set pgaudit.log_client='on';,<not logged>
SET

**1.  ALL is set, then add -MISC**
postgres=# set pgaudit.log='all, -ddl';
NOTICE:  AUDIT: SESSION,5,1,MISC,SET,,,"set pgaudit.log='all, -ddl';",<not logged>
SET
postgres=# set pgaudit.log='all, -ddl, -role';
NOTICE:  AUDIT: SESSION,6,1,MISC,SET,,,"set pgaudit.log='all, -ddl, -role';",<not logged>
SET
postgres=# set pgaudit.log='all, -ddl, -role, -misc';
SET
>when -misc is set, this set command is not audited

**2. MISC is set, then remove MISC**
postgres=# set pgaudit.log='ddl, role, misc';
NOTICE:  AUDIT: SESSION,7,1,MISC,SET,,,"set pgaudit.log='ddl, role, misc';",<not logged>
SET
postgres=# set pgaudit.log='ddl, misc';
NOTICE:  AUDIT: SESSION,8,1,MISC,SET,,,"set pgaudit.log='ddl, misc';",<not logged>
SET
postgres=# set pgaudit.log='ddl, role';
SET
>when misc option is removed, this set command is not audited

3. Either ALL or MISC is set, then set NONE
postgres=# set pgaudit.log='all, -ddl';
NOTICE:  AUDIT: SESSION,9,1,MISC,SET,,,"set pgaudit.log='all, -ddl';",<not logged>
SET
postgres=# set pgaudit.log='none';
SET
postgres=# set pgaudit.log='misc, ddl';
NOTICE:  AUDIT: SESSION,10,1,MISC,SET,,,"set pgaudit.log='misc, ddl';",<not logged>
SET
postgres=# set pgaudit.log='none';
SET
>when none option is set, no audit

**Comment by soulhunter** [comment]
Hello,

In a kind of hacky way, and not having enough knowledge of this project yet, I believe function check_pgaudit_log could be modified to log whenever pgaudit.log is even attempted to be modified.

A friend of I said that he believes it should be possible to modify function log_audit_event to just always log configuration changes to pgAudit.

IMHO, pgAudit should log any attempt to modify its configuration.  Of course, superusers have the rights to change them, but as an audit system it should make some noise if it is being re-configured.

Sincerely,

Ildefonso

**Comment by dwsteele** [comment]
GUCs can change frequently during a session so logging every change to `pgaudit.*` may be pretty noisy.

Only the superuser can change these GUCs and there are numerous ways that the superuser can circumvent/modify logging.  It is not the goal of this extension to audit the superuser.

**Comment by mark-it-allen-db** [comment]
Can this be considered for re-opening ? All we want is 1 more logged event (we can capture nefarious actions like turning off audit logging in downstream event monitoring - e.g. on GCP Cloud SQL Postgres -> Audit logging.)

**Comment by dwsteele** [comment]
No. These GUCs may only be changed by the superuser and there is no way to reliably audit the superuser with pgaudit. You can use the set_user extension (https://github.com/pgaudit/set_user) to reliably log superuser commands.
