### ISSUE TITLE
pgaudit crashing postgres.

### ISSUE THREAD

**Issue by lesmurray** [pgaudit/pgaudit#79]
Built pgaudit successfully two different ways off of RELEASE_9_6_STABLE, once through Visual Studio, once via MSYS build.  We currently use the 9.6.3 postgres in our product.  Upon placing the dll and sql files in the proper location, added the pgaudit to the extensions using the ALTER command.  Once the pgaudit is added to the extensions and postgres restarted it always crashes.  Have rebuilt several times.  (a) Will the RELEASE_9_6_STABLE branch of pgaudit not be compatible with 9.6.3?  (b) Is there any way to debug what is happening?  I don't see any logs or anything?  (c) Is there any gotyas that you can think of that might be causing the crash?  (d) Why can't binaries be delivered for windows for pgaudit.  It certainly would make it more likely to get used.  It took a lot of noodling to get the thing to build.

**Comment by Demacr** [comment]
Have you tried to build using gcc in windows?

**Comment by lesmurray** [comment]
I built it with the msys, turns out that won't work due to it being a 32 bit dll that is generated even though I used all the 64 bit tools.  I then built it with visual studio and got a 64 bit dll.  Unfortunately it seems to mostly load.  It loads without errors but when I do show shared_preload_libraries, it shows 1 library loaded, but shows a blank line.  When I try to create the extension, it fails saying that it isn't loaded.  So it is kind of present, seems to get loaded, but something is causing the display of a blank line rather than the name of the dll.  I haven't found build instructions for doing it with gcc on windows.  I just wish the dll was posted so that didn't have to go through all this torture.

**Comment by lesmurray** [comment]
Here is the output: 
postgres=# show shared_preload_libraries;
 shared_preload_libraries
----------------------------

(1 row)

**Comment by lesmurray** [comment]
I have found that I cannot add the dll to a EDB postgres installation.  I can get it to work only if I do a full install from the build using both postgres and pgaudit from that build.  Since it is a DLL, I'm at a loss as to why they aren't compatible as I'm using exactly the same code versions, but it causes heap corruption crashes 100% of the time.  Causing us to totally redesign the install infrastructure with the database.
