### ISSUE TITLE
unexpected logging of selects from ri-triggers

### ISSUE THREAD

**Issue by akretschmer2ndq** [pgaudit/pgaudit#80]
Hi all,

with version 1.4 and PG 11 and this settings:

```
pgaudit.log = 'ddl'
pgaudit.role = 'audit'
```

and

```
grant insert, update, delete on child to audit;
grant insert, update, delete on parent to audit;

```
we want to achive logging of all DDL-commands and all DML-commands on those 2 particular tables, but pgaudit loggs also selects fired from RI-Triggers:

```
CREATE TABLE parent (
   id SERIAL PRIMARY KEY,
   customer_id INTEGER,
   ship_to VARCHAR (255)
);


CREATE TABLE child(
   item_id INTEGER NOT NULL,
   so_id INTEGER,
   PRIMARY KEY (item_id, so_id),
   FOREIGN KEY (so_id) REFERENCES parent (id)
);


grant insert, update, delete on child to audit;
grant insert, update, delete on parent to audit;



INSERT INTO parent 
    (id,customer_id,ship_to)
VALUES (
 1,4711,'London');


INSERT INTO child
    (item_id,so_id)
        VALUES(1,1);

```
and you will find in the log:

```
2020-02-07 13:53:15 UTC [13810]: [23-1] user=xyz,db=xyz LOG:  00000: AUDIT: OBJECT,10,1,WRITE,INSERT,TABLE,xyz.child,"INSERT INTO child
                (item_id,so_id)
                        VALUES(1,1);",<none>
2020-02-07 13:53:15 UTC [13810]: [24-1] user=xyz,db=xyz LOCATION:  log_audit_event, pgaudit.c:774
2020-02-07 13:53:15 UTC [13810]: [25-1] user=xyz,db=xyz LOG:  00000: AUDIT: OBJECT,10,2,WRITE,UPDATE,TABLE,xyz.parent,"SELECT 1 FROM ONLY ""xyz"".""parent"" x WHERE ""id"" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x",1
```

The last line is the problem, this select is generated from the RI-Trigger.

Normal selects on those tables are not logged (as expected), but selects fired by RI-Trigger are loggend. Is there a way to get rid of logging of those ri-trigger-selects?

**Comment by simonat2ndQuadrant** [comment]
On Thu, 13 Feb 2020 at 12:11, akretschmer2ndq <notifications@github.com>
wrote:

> Hi all,
>
> with version 1.4 and PG 11 and this settings:
>
...

> 2020-02-07 13:53:15 UTC [13810]: [23-1] user=xyz,db=xyz LOG:  00000: AUDIT: OBJECT,10,1,WRITE,INSERT,TABLE,xyz.child,"INSERT INTO child
>
>                 (item_id,so_id)
>                         VALUES(1,1);",<none>
> 2020-02-07 13:53:15 UTC [13810]: [24-1] user=xyz,db=xyz LOCATION:  log_audit_event, pgaudit.c:774
> 2020-02-07 13:53:15 UTC [13810]: [25-1] user=xyz,db=xyz LOG:  00000: AUDIT: OBJECT,10,2,WRITE,UPDATE,TABLE,xyz.parent,"SELECT 1 FROM ONLY ""xyz"".""parent"" x WHERE ""id"" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x",1
>
> The last line is the problem, this select is generated from the RI-Trigger.
>
> Normal selects on those tables are not logged (as expected), but selects
> fired by RI-Trigger are loggend. Is there a way to get rid of logging of
> those ri-trigger-selects?
>
PostgreSQL docs say

"The use of FOR NO
KEY UPDATE, FOR UPDATE, FOR SHARE or FOR KEY SHARE requires UPDATE
privilege as
well (for at least one column of each table so selected)."

pgaudit then decides that if it needs UPDATE permission, it must be an
action of type WRITE

That is based upon permissions, not on statement type. So some rework would
be required to trap and filter out those. But its possible, with work.

-- 
Simon Riggs                http://www.2ndQuadrant.com/
<http://www.2ndquadrant.com/>
PostgreSQL Solutions for the Enterprise

**Comment by bs1008** [comment]
@simonat2ndQuadrant do you have an UPDATE for us, we are still waiting for a solution on this issue. What are the next steps to solve our problem ?

**Comment by dwsteele** [comment]
This generally happens when auditing the superuser, i.e. `postgres`.  Here's how we currently filter FK queries and queries in security definer functions: https://github.com/pgaudit/pgaudit/blob/master/pgaudit.c#L994

We are open to suggestions on a better way to do this.
