### ISSUE TITLE
ignore some relation access logs

### ISSUE THREAD

**Issue by colin-lee** [pgaudit/pgaudit#81]
add configuration like this:
pgaudit.ignore_relation = "public.temp1,another_schema.temp2"

then, audit log will skip CRUD events on "public.temp1" or "another_schema.temp2"

**Comment by dwsteele** [comment]
This seems pretty limited.  Better would be to implement something like `pgaudit.role_ignore` that works like `pgaudit.role` but ignores everything in that role.

We don't currently have any plans to implement such a feature, however.
