### ISSUE TITLE
can not run make check and make install for PG11

### ISSUE THREAD

**Issue by rakehell1986** [pgaudit/pgaudit#82]
tigersdeMacBook-Pro-2:PostgreSQL tigershome$ make -C ./pgaudit install USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/Users/tigershome/PostgreSQL/pg11/include/postgresql/server -I/Users/tigershome/PostgreSQL/pg11/include/postgresql/internal  -I/opt/pgbin-build/pgbin/bin/../shared/osx_64/include -I/usr/include/libxml2   -c -o pgaudit.o pgaudit.c
In file included from pgaudit.c:26:
In file included from /Users/tigershome/PostgreSQL/pg11/include/postgresql/server/libpq/auth.h:17:
/Users/tigershome/PostgreSQL/pg11/include/postgresql/server/libpq/libpq-be.h:23:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [pgaudit.o] Error 1

**Comment by rakehell1986** [comment]
tigersdeMacBook-Pro-2:pgaudit tigershome$ make check USE_PGXS=1
"/Applications/Xcode.app/Contents/Developer/usr/bin/make check" is not supported.
Do "/Applications/Xcode.app/Contents/Developer/usr/bin/make install", then "/Applications/Xcode.app/Contents/Developer/usr/bin/make installcheck" instead.
tigersdeMacBook-Pro-2:pgaudit tigershome$

**Comment by rakehell1986** [comment]
tigersdeMacBook-Pro-2:pgaudit tigershome$ make install USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/Users/tigershome/PostgreSQL/pg11/include/postgresql/server -I/Users/tigershome/PostgreSQL/pg11/include/postgresql/internal  -I/opt/pgbin-build/pgbin/bin/../shared/osx_64/include -I/usr/include/libxml2   -c -o pgaudit.o pgaudit.c
In file included from pgaudit.c:26:
In file included from /Users/tigershome/PostgreSQL/pg11/include/postgresql/server/libpq/auth.h:17:
/Users/tigershome/PostgreSQL/pg11/include/postgresql/server/libpq/libpq-be.h:23:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [pgaudit.o] Error 1
tigersdeMacBook-Pro-2:pgaudit tigershome$

**Comment by adrianlzt** [comment]
Try installing openssl-devel
