### ISSUE TITLE
Error during installation in PG 12

### ISSUE THREAD

**Issue by c2430** [pgaudit/pgaudit#83]
pgaudit.c:11:10: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
          ^~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'pgaudit.o' failed
make: *** [pgaudit.o] Error 1

 make install USE_PGXS=1 after this i'm getting above error.
PG version 12.2
Pgaudit: 1.4.0

**Comment by adrianlzt** [comment]
do you have installed ``postgresql12-devel`` ?
