### ISSUE TITLE
CREATE EXTENSION problem

### ISSUE THREAD

**Issue by harada-toshi** [pgaudit/pgaudit#9]
# "CREATE EXTENSION" problem.

Hi.
I am testing the pgaudit(https://github.com/pgaudit/pgaudit) on PostgeSQL 9.5.1.

## Problem
By vaue of "pgaudit.log" , there is a case in which "CREATE EXTENTION" occurs error.

* pgaudit.log = 'none' ->  normal end, and event-trigger is registered.
```
$ psql -U postgres newdb -c "SHOW pgaudit.log"
 pgaudit.log
-------------
 none
(1 row)

$ psql -U postgres newdb -c "CREATE EXTENSION pgaudit"
CREATE EXTENSION
$ psql -U postgres newdb -c "DROP EXTENSION pgaudit"
DROP EXTENSION
$
```
* pgaudit.log = 'all' -> "CREATE EXTENSION" occures error.

```
$ psql -U postgres newdb -c "SHOW pgaudit.log"
 pgaudit.log
-------------
 all
(1 row)

$ psql -U postgres newdb -c "CREATE EXTENSION pgaudit"
ERROR:  pg_event_trigger_ddl_commands() can only be called in an event trigger function
CONTEXT:  SQL statement "SELECT UPPER(object_type), object_identity, UPPER(command_tag)
  FROM pg_catalog.pg_event_trigger_ddl_commands()"
$
```

**Comment by jbscalia** [comment]
I'm using the latest copy of pgaudit-master which was downloaded this past week (the end of 2016) and just received the exact error on a new test database I was building. Note that the database is named pgaudit. Here's the log output:

2017-01-06 07:54:35.475 EST,"s45198","pgaudit",19640,"[local]",586f937c.4cb8,12,"CREATE EXTENSION",2017-01-06 07:54:20 EST,3/858,1008242,ERROR,39P03,"pg_event_trigger_ddl_commands() can only be called in an event trigger function",,,,,"SQL statement ""SELECT UPPER(object_type), object_identity, UPPER(command_tag)

So, it might be that this wasn't fixed after all. Or I am doing something very bad?

**Comment by dwsteele** [comment]
I don't think this is the same issue.  Please see the last paragraph in this section https://github.com/pgaudit/pgaudit/blob/master/README.md#settings and see it that answers your question.

**Comment by jbscalia** [comment]
Thanks, David. I just managed to fix the issue by resetting the pgaudit.log
to null in the database, then I loaded the extension, and finally, I reset
the pgaudit.log setting back to its original setting. I had originally
misinterpreted the instructions and did not realize there was an
environment setting with this name.  Seems better now, and I'm resuming
testing.
