### ISSUE TITLE
Filterout liveliness check logs

### ISSUE THREAD

**Issue by rverma-jm** [pgaudit/pgaudit#90]
in our db, we have db liveliness check enabled by basic sql query. This result in a log statement as 
`AUDIT: SESSION,1441,1,READ,SELECT,,,SELECT 1,<not logged>` after every few line.
Is there a way to tell pg_audit not to capture these select statements at all.

**Comment by dwsteele** [comment]
There is no way to filter out a specific statement in pgaudit.

The easiest solution is to do your check with a role that is not audited or against a table that is not audited.
