### ISSUE TITLE
make check or make install fail for RHEL_11_STABLE for pgAudit 1.3.1

### ISSUE THREAD

**Issue by meiravRath** [pgaudit/pgaudit#93]
Hello,

I'm trying to install pgaudit on a RHEL 7.3 with PostgreSQL 11 and following the installation rules in pgaudit readme. 

I'm having trouble with make check, and it differs between installing from a git-brought directory or unpacking the tar.gz file available for download.

**tag.gz file:**
I unloaded the tar.gz file to /tmp/ and ran:

> [root@meiravPostgreSQL11aUDIT0 tmp]# su - postgres
>Last login: Tue Apr 28 11:54:42 IDT 2020 on pts/0
>-bash-4.2$ cd /tmp/pgaudit-1.3.1
>-bash-4.2$ make check USE_PGXS=1
>Makefile:16: /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
>make: *** No rule to make target `/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

Tried to just run make and got:

>-bash-4.2$ make
>Makefile:20: ../../src/Makefile.global: No such file or directory
>Makefile:21: /contrib/contrib-global.mk: No such file or directory
>make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.

**git brought package:**

Got a different error when following instructions in the readme file, but got the same error when just running make:

> [root@meiravPostgreSQL11aUDIT0 tmp]# git clone https://github.com/pgaudit/pgaudit.git
> Cloning into 'pgaudit'...
> remote: Enumerating objects: 463, done.
> remote: Total 463 (delta 0), reused 0 (delta 0), pack-reused 463
> Receiving objects: 100% (463/463), 909.73 KiB | 1.39 MiB/s, done.
> Resolving deltas: 100% (261/261), done.
> [root@meiravPostgreSQL11aUDIT0 tmp]# cd pgaudit
> [root@meiravPostgreSQL11aUDIT0 pgaudit]# pwd
> /tmp/pgaudit
> [root@meiravPostgreSQL11aUDIT0 pgaudit]# git checkout REL_11_STABLE
> Branch REL_11_STABLE set up to track remote branch REL_11_STABLE from origin.
> Switched to a new branch 'REL_11_STABLE'
> [root@meiravPostgreSQL11aUDIT0 pgaudit]# make check USE_PGXS=1
> make: pg_config: Command not found
> make: *** No rule to make target `check'.  Stop.
> [root@meiravPostgreSQL11aUDIT0 pgaudit]# make install USE_PGXS=1
> make: pg_config: Command not found
> make: *** No rule to make target `install'.  Stop.
> [root@meiravPostgreSQL11aUDIT0 pgaudit]# make check
> Makefile:20: ../../src/Makefile.global: No such file or directory
> Makefile:21: /contrib/contrib-global.mk: No such file or directory
> make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.

What am I doing wrong?

**Comment by iamstraderb** [comment]
pg_config not being found is due to it not being in your PATH. This can be set at runtime by:
`export PATH=$PATH:/usr/pgsql-11/bin`

To persistently set this, the vagrantfile in test/Vagrantfile includes:
```
# Setup environment
echo 'export PG_VERSION=11' >> /etc/bashrc
echo 'export PATH=$PATH:/usr/pgsql-${PG_VERSION?}/bin' >> /etc/bashrc
source /etc/bashrc
```

**Comment by rklaus77** [comment]
Same issue

[postgres@p-dqb-db1 pgaudit]$ pg_config --pgxs
/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$ make check USE_PGXS=1
"make check" is not supported.
Do "make install", then "make installcheck" instead.
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$ make install USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgaudit.o pgaudit.c
pgaudit.c:16:29: fatal error: access/relation.h: No such file or directory
 #include "access/relation.h"
                             ^
compilation terminated.
make: *** [pgaudit.o] Error 1
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$ make install
Makefile:22: ../../src/Makefile.global: No such file or directory
Makefile:23: /usr/pgsql-11/lib/pgxs//contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-11/lib/pgxs//contrib/contrib-global.mk'.  Stop.
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$ which pg_config
/usr/pgsql-11/bin/pg_config
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$
[postgres@p-dqb-db1 pgaudit]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lib/oracle/12.2/client64/bin:/usr/pgsql-11/bin:/home/postgres/.local/bin:/home/postgres/bin
