### ISSUE TITLE
drop extension does not work

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#94]
I found an issue for drop extension behavior during using the pgaudit.  The audit log printed even if I drop extension pgaudit.
Would you please help to have a check?
-----------------------------------------------------
Issue Description:
use command "drop extension pgaudit" and also restar PG via pg_ctl stop, start . But I found the pgaudit still works well. There were audit log printed into the logfile.

Steps:
step-1: create extension
postgres=# create extension pgaudit;
CREATE EXTENSION
postgres=# select * from test;
Message in log file:
May 10 22:19:29 localhost postgres[2593]: [283-1] LOG:  AUDIT: SESSION,24,1,READ,SELECT,TABLE,public.test,select * from test;,<none>
step-2: drop extension pgaudit;
postgres=# drop extension pgaudit;
DROP EXTENSION
postgres=# select * from test;
Message in log file:
May 10 22:20:23 localhost postgres[2593]: [285-1] LOG:  AUDIT: SESSION,26,1,READ,SELECT,TABLE,public.test,select * from test;,<none>

Issue:
Actually, the second log shall not be printed after drop extension.
I got same result even if restart the pg service.

Would you please help to check if this is sure an issue? Thanks very much inadvance.
Now I am debugging the related code to verify if there is sure an bug exist.

Best wishes,
Hope Gao

**Comment by dwsteele** [comment]
You'll need to remove pgaudit from `shared_preload_libraries` to uninstall it entirely.

**Comment by gaoxueyu** [comment]
thank you very much.
