### ISSUE TITLE
Audit for partitioned table does not support well

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#95]
There is an issue for partitioned table. The object type is UNKNOW.

Test scenario:

Audit Log:
May 13 03:51:34 localhost postgres[2204]: [49-1] LOG:  AUDIT: SESSION,21,1,READ,SELECT,UNKNOWN,public.hope,select * from hope;,<none>

Suppose the log shall as below:
LOG:  AUDIT: SESSION,2,1,READ,SELECT,PARTITIONED TABLE,public.hope,select * from hope;,<none>

-------------
I am very intrested in pgaudit project and I know how to fix this issue. 
It's my plesure to fix the issue as the contributor.

Thanks very much in advance.

Best wishes,
Hope Gao

**Comment by gaoxueyu** [comment]
sorry the test scenario is missed.

step-1:  create partition table as below:
create table hope(x int ,y int) partition by hash(x);
create table hope_0 partition of hope for values with ( modulus 2, remainder 0); 
create table hope_1 partition of hope for values with ( modulus 2, remainder 1); 

step-2:  execute sql command
select * from hope;

**Comment by dwsteele** [comment]
Go for it. Be sure to include regression tests with your PR. Please work against master, I'll backpatch as needed.

**Comment by gaoxueyu** [comment]
@dwsteele Hi David, I submit the code in my PR.  Please help to have a check. Thanks very much in advance.

by the way, the output file in expected folder seems not correct for official master branch, I opened a new bug to trace it.
