### ISSUE TITLE
The output file in expected folder is wrong for regression testing

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#97]
Pull the latest official version of pgaudit, then run regression testing, the result is failed.
I double check the statement id in expected/pgaudit.out is NOT correct. Would you please help to have a check?

I diffed the result manually with offical one, the diffrences are as below:
=========================
[postgres@localhost ~]$ diff pgaudit.out  /home/postgres/pgaudit/expected/pgaudit.out
8c8
< NOTICE:  AUDIT: SESSION,4,1,MISC,SET,,,SET pgaudit.log_level = 'notice';,<not logged>
---
> NOTICE:  AUDIT: SESSION,3,1,MISC,SET,,,SET pgaudit.log_level = 'notice';,<not logged>
10c10
< NOTICE:  AUDIT: SESSION,5,1,DDL,CREATE TABLE,TABLE,public.tmp,"CREATE TABLE tmp (id int, data text);",<not logged>
---
> NOTICE:  AUDIT: SESSION,4,1,DDL,CREATE TABLE,TABLE,public.tmp,"CREATE TABLE tmp (id int, data text);",<not logged>
12,13c12,13
< NOTICE:  AUDIT: SESSION,6,1,READ,SELECT,,,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
< NOTICE:  AUDIT: SESSION,6,2,DDL,CREATE TABLE AS,TABLE,public.tmp2,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
---
> NOTICE:  AUDIT: SESSION,5,1,READ,SELECT,,,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
> NOTICE:  AUDIT: SESSION,5,2,DDL,CREATE TABLE AS,TABLE,public.tmp2,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
============================

The statements in sql/pgaudit.sql are as below:
============================
\set VERBOSITY terse
-- Create pgaudit extension
CREATE EXTENSION IF NOT EXISTS pgaudit;
-- Make sure events don't get logged twice when session logging
SET pgaudit.log = 'all';
SET pgaudit.log_client = ON;
SET pgaudit.log_level = 'notice';
CREATE TABLE tmp (id int, data text);
CREATE TABLE tmp2 AS (SELECT * FROM tmp);
==============================

The correct result shall be:
==============================
\set VERBOSITY terse
-- Create pgaudit extension
CREATE EXTENSION IF NOT EXISTS pgaudit;
-- Make sure events don't get logged twice when session logging
SET pgaudit.log = 'all';
SET pgaudit.log_client = ON;
SET pgaudit.log_level = 'notice';
NOTICE:  AUDIT: SESSION,4,1,MISC,SET,,,SET pgaudit.log_level = 'notice';,<not logged>
CREATE TABLE tmp (id int, data text);
NOTICE:  AUDIT: SESSION,5,1,DDL,CREATE TABLE,TABLE,public.tmp,"CREATE TABLE tmp (id int, data text);",<not logged>
CREATE TABLE tmp2 AS (SELECT * FROM tmp);
NOTICE:  AUDIT: SESSION,6,1,READ,SELECT,,,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
NOTICE:  AUDIT: SESSION,6,2,DDL,CREATE TABLE AS,TABLE,public.tmp2,CREATE TABLE tmp2 AS (SELECT * FROM tmp);,<not logged>
==============================

Best wishes,
Hope

**Comment by dwsteele** [comment]
pgaudit `master` is still intended to compile against PG12. There's a separate PR (#100) for updating to PG13 but we are waiting for beta1 later this week.

For now can you test against `REL_12_STABLE`?

**Comment by gaoxueyu** [comment]
@dwsteele Hi David, thanks for your response.
But seems there is misleading for my description, I used the pgaudit master branch and PG12 for testing (git clone https://github.com/pgaudit/pgaudit.git).

For what you mentioned "test against REL_12_STABLE", seems no this branch exists.

git checkout REL_12_STABLE
error: pathspec 'REL_12_STABLE' did not match any file(s) known to git.

**Comment by gaoxueyu** [comment]
@dwsteele Hi David, I did more testing today and found the root cause for it.
This is due to I set pgaudit.log = 'all' in postgresql.conf before running the regression test case.

**Comment by dwsteele** [comment]
> git checkout REL_12_STABLE

I meant REL_12_STABLE in the postgres git repo, but looks like you figured it out anyway.

Yes, the regression tests should be run from a completely clean environment.
