### ISSUE TITLE
Can we support json log output

### ISSUE THREAD

**Issue by rverma-jm** [pgaudit/pgaudit#98]
A lot of logging frameworks are now a days has better functionalities in consuming and analysing json logs. E.g elasticsearch/ kinesis firehose./ cloudwatch logs

By generating json logs directly we can skip an intermediate layer to convert the already structured data into another structure.

If this is already possible, i can't find documents.

**Comment by dwsteele** [comment]
The best solution (that we know of) is to configure PostgreSQL to output CSV logs:
```
log_destination = 'csvlog'
```
