### ISSUE TITLE
Ideas for auditing the error log

### ISSUE THREAD

**Issue by gaoxueyu** [pgaudit/pgaudit#99]
Current version for pgAudit has some limitations, like statements that are executed after a transaction enters an aborted state will not be audit logged.
But I think the error message is most important for customers and shall be audited into log.

I did some investigation on error message auditing. But there are many works need to be done in future. Just list my initial solution, and the demo log.
Step-1: involve the emit_log_hook
Step-2: in emit_log_hook function, check if it is an error statement. 
Filter the error log level (make sure edata->elevel is 20） and query string(make sure  debug_query_string is Not NULL). 
Step-3: if the error statement shall be audited, call the send_message_to_server_log () to rewrite the log with audit format.

Demo log to record select from a non-existing table:
May 17 21:37:10 localhost postgres[2259]: [4-1] ERROR:  AUDIT: ,,,DML,,,,select * from aa;,,10,FAIL,
10,FAIL is added in my testing, 10 stands for user id and FAIL stands for this is an error audit log

Not sure if you are interested in this solution. If yes, I can do further investigation on it.
Most welcome if you have any comments.

Thanks,
Hope.Gao

**Comment by dwsteele** [comment]
This isn't quite right because *previous* statements are also now errored (i.e. not applied) but only the last statement gets labelled that way. A better way to do it is to track the statements in the transaction and mark them all as errored with the transaction errors. This is what https://github.com/pgaudit/pgaudit_analyze does.

**Comment by gaoxueyu** [comment]
Hi David, thanks very much for your comments.
I will have further study on "https://github.com/pgaudit/pgaudit_analyze ".
